"""DeckTalk: narrated presentation videos, cut to the word.

A project is a directory. `decktalk.open(path)` returns a project, six verbs move it forward, and a
handful of calls report on it, cut a piece out of it or serve it. Every call returns a frozen result
whose findings are diagnostics with a code, a location, a certainty and often a fix a caller can
apply. Every call opens a run and writes to one event stream, which any renderer subscribes to.
Nothing in this package prints, nothing reads the environment except `Machine.from_environment`, and
a path a result carries is always relative to the project root.

`__all__` is the whole supported Python API. It is generated, and it is the closure of every type
reachable from an exported annotation, so a type a result can hand you is a type you can import.
Everything not in it may move without notice.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .artifacts import (
    CUE_AT,
    CUE_SEPARATOR,
    PLACEHOLDER_PREFIX,
    PREVIEW_ALIAS,
    TAKE_DIGITS,
    WORDS_SUFFIX,
    CueTimes,
    Cut,
    Cuts,
    Luma,
    PlaceholderInputs,
    RecordingChecks,
    RecordingLog,
    Stored,
    Take,
    TakeInputs,
    Takes,
    Words,
    file_digest,
    input_hash,
    is_placeholder,
    take_file,
    text_digest,
    words_file,
)
from .errors import (
    ApprovalRequired,
    Cancel,
    Cancelled,
    DeckTalkError,
    ErrorCode,
    ErrorInfo,
    InputError,
    NotBuiltError,
    ProjectLocked,
    ProviderError,
    ToolError,
)
from .events import (
    Event,
    Events,
    Fetch,
    FindingEvent,
    JsonlSink,
    Level,
    Line,
    Log,
    Progress,
    RunDone,
    RunStart,
    SectionDone,
    SectionStart,
    SpendEvent,
    StageDone,
    StageStart,
    Subscription,
    Unit,
)
from .explain import Explanation, NumberView, explain
from .findings import (
    Applicability,
    Certainty,
    Code,
    CommandFix,
    Edit,
    EditFix,
    Finding,
    Fix,
    Location,
    RaisedBy,
    SettingFix,
)
from .inputs import (
    ENV_FILE,
    ClipSection,
    CuedSection,
    Document,
    Env,
    Inputs,
    Markers,
    Mix,
    MixEffect,
    MusicSpec,
    PageSection,
    Section,
    Segment,
    Soundscape,
    SoundSpec,
    Transition,
    Voice,
    Workspace,
)
from .machine import Machine, Run, Toolchain, init
from .media.pagereport import (
    Box,
    CueRow,
    ElementRow,
    FrameGap,
    LongFrame,
    PageReport,
    PageWarningRow,
    SceneCatalog,
    WordRow,
)
from .pipeline import PIPELINE, Artifact, Outcome, Stage, StageSpec
from .project import Origin, Project, open, section_numbers
from .results import (
    ApplyResult,
    AssembleResult,
    BuildResult,
    CheckResult,
    ClipResult,
    ConfigExplainResult,
    ConfigGetResult,
    ConfigListResult,
    ConfigSetResult,
    ConfigUnsetResult,
    CueCheck,
    CueResult,
    CueTime,
    CutCheck,
    DoctorResult,
    ErrorResult,
    FixOutcome,
    InitResult,
    InstalledTool,
    InstallResult,
    Layer,
    LiveRun,
    Loudness,
    NarrateResult,
    Panel,
    RecordResult,
    RenderedSection,
    Result,
    Scope,
    SeamCheck,
    SectionCues,
    SectionKind,
    SectionRecording,
    SectionStatus,
    SectionTake,
    SectionWords,
    ServeResult,
    SettingValue,
    SkipReason,
    SoundItem,
    SoundKind,
    SoundscapeResult,
    SoundStatus,
    Spend,
    SpendState,
    StageRun,
    StartCheck,
    StatusResult,
    StoryboardResult,
    Substitute,
    TakeStatus,
    VerifyResult,
    Voicing,
    Word,
    WordsResult,
)
from .settings import LayerValue
from .tomlmap import Nature, Source

try:
    __version__ = version("decktalk")
except PackageNotFoundError:  # running from a checkout without an install
    __version__ = "0+unknown"

__all__ = [
    "Applicability",
    "ApplyResult",
    "ApprovalRequired",
    "Artifact",
    "AssembleResult",
    "Box",
    "BuildResult",
    "CUE_AT",
    "CUE_SEPARATOR",
    "Cancel",
    "Cancelled",
    "Certainty",
    "CheckResult",
    "ClipResult",
    "ClipSection",
    "Code",
    "CommandFix",
    "ConfigExplainResult",
    "ConfigGetResult",
    "ConfigListResult",
    "ConfigSetResult",
    "ConfigUnsetResult",
    "CueCheck",
    "CueResult",
    "CueRow",
    "CueTime",
    "CueTimes",
    "CuedSection",
    "Cut",
    "CutCheck",
    "Cuts",
    "DeckTalkError",
    "DoctorResult",
    "Document",
    "ENV_FILE",
    "Edit",
    "EditFix",
    "ElementRow",
    "Env",
    "ErrorCode",
    "ErrorInfo",
    "ErrorResult",
    "Event",
    "Events",
    "Explanation",
    "Fetch",
    "Finding",
    "FindingEvent",
    "Fix",
    "FixOutcome",
    "FrameGap",
    "InitResult",
    "InputError",
    "Inputs",
    "InstallResult",
    "InstalledTool",
    "JsonlSink",
    "Layer",
    "LayerValue",
    "Level",
    "Line",
    "LiveRun",
    "Location",
    "Log",
    "LongFrame",
    "Loudness",
    "Luma",
    "Machine",
    "Markers",
    "Mix",
    "MixEffect",
    "MusicSpec",
    "NarrateResult",
    "Nature",
    "NotBuiltError",
    "NumberView",
    "Origin",
    "Outcome",
    "PIPELINE",
    "PLACEHOLDER_PREFIX",
    "PREVIEW_ALIAS",
    "PageReport",
    "PageSection",
    "PageWarningRow",
    "Panel",
    "PlaceholderInputs",
    "Progress",
    "Project",
    "ProjectLocked",
    "ProviderError",
    "RaisedBy",
    "RecordResult",
    "RecordingChecks",
    "RecordingLog",
    "RenderedSection",
    "Result",
    "Run",
    "RunDone",
    "RunStart",
    "SceneCatalog",
    "Scope",
    "SeamCheck",
    "Section",
    "SectionCues",
    "SectionDone",
    "SectionKind",
    "SectionRecording",
    "SectionStart",
    "SectionStatus",
    "SectionTake",
    "SectionWords",
    "Segment",
    "ServeResult",
    "SettingFix",
    "SettingValue",
    "SkipReason",
    "SoundItem",
    "SoundKind",
    "SoundSpec",
    "SoundStatus",
    "Soundscape",
    "SoundscapeResult",
    "Source",
    "Spend",
    "SpendEvent",
    "SpendState",
    "Stage",
    "StageDone",
    "StageRun",
    "StageSpec",
    "StageStart",
    "StartCheck",
    "StatusResult",
    "Stored",
    "StoryboardResult",
    "Subscription",
    "Substitute",
    "TAKE_DIGITS",
    "Take",
    "TakeInputs",
    "TakeStatus",
    "Takes",
    "ToolError",
    "Toolchain",
    "Transition",
    "Unit",
    "VerifyResult",
    "Voice",
    "Voicing",
    "WORDS_SUFFIX",
    "Word",
    "WordRow",
    "Words",
    "WordsResult",
    "Workspace",
    "__version__",
    "explain",
    "file_digest",
    "init",
    "input_hash",
    "is_placeholder",
    "open",
    "section_numbers",
    "take_file",
    "text_digest",
    "words_file",
]
