"""DeckTalk: narrated presentation videos, cut to the word.

A project is a directory. `decktalk.open(path)` returns a project, six verbs move it forward, and a
handful of calls report on it, cut a piece out of it or serve it. Every call returns a frozen result
whose findings are diagnostics with a code, a location, a certainty and often a fix a caller can
apply. Every call opens a run and writes to one event stream, which any renderer subscribes to.
Nothing in this package prints, nothing reads the environment except `Machine.from_environment`, and
a path a result carries is always relative to the project root.

`__all__` is the whole supported Python API. It is generated, and it is the closure of every type
reachable from an exported annotation, so a type a result can hand you is a type you can import.
Everything not in it may move without notice.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .errors import (
    ApprovalRequired,
    Cancel,
    Cancelled,
    DeckTalkError,
    ErrorCode,
    ErrorInfo,
    InputError,
    NotBuiltError,
    ProjectLocked,
    ProviderError,
    ToolError,
)
from .events import (
    Event,
    Events,
    Fetch,
    FindingEvent,
    JsonlSink,
    Level,
    Line,
    Log,
    Progress,
    RunDone,
    RunStart,
    SectionDone,
    SectionStart,
    SpendEvent,
    StageDone,
    StageStart,
    Subscription,
    Unit,
)
from .findings import (
    Applicability,
    Certainty,
    Code,
    CommandFix,
    Edit,
    EditFix,
    Finding,
    Fix,
    Location,
    RaisedBy,
    SettingFix,
)
from .pipeline import PIPELINE, Artifact, Outcome, Stage, StageSpec
from .results import (
    ApplyResult,
    AssembleResult,
    BuildResult,
    CheckResult,
    ClipResult,
    ConfigExplainResult,
    ConfigGetResult,
    ConfigListResult,
    ConfigSetResult,
    ConfigUnsetResult,
    CueCheck,
    CueResult,
    CueTime,
    CutCheck,
    DoctorResult,
    ErrorResult,
    FixOutcome,
    InitResult,
    InstalledTool,
    InstallResult,
    Layer,
    LiveRun,
    Loudness,
    NarrateResult,
    Panel,
    RecordResult,
    RenderedSection,
    Result,
    Scope,
    SeamCheck,
    SectionCues,
    SectionKind,
    SectionRecording,
    SectionStatus,
    SectionTake,
    SectionWords,
    ServeResult,
    SettingValue,
    SkipReason,
    SoundItem,
    SoundKind,
    SoundscapeResult,
    SoundStatus,
    Spend,
    SpendState,
    StageRun,
    StartCheck,
    StatusResult,
    StoryboardResult,
    Substitute,
    TakeStatus,
    VerifyResult,
    Voicing,
    Word,
    WordsResult,
)

try:
    __version__ = version("decktalk")
except PackageNotFoundError:  # running from a checkout without an install
    __version__ = "0+unknown"

__all__ = [
    "Applicability",
    "ApplyResult",
    "ApprovalRequired",
    "Artifact",
    "AssembleResult",
    "BuildResult",
    "Cancel",
    "Cancelled",
    "Certainty",
    "CheckResult",
    "ClipResult",
    "Code",
    "CommandFix",
    "ConfigExplainResult",
    "ConfigGetResult",
    "ConfigListResult",
    "ConfigSetResult",
    "ConfigUnsetResult",
    "CueCheck",
    "CueResult",
    "CueTime",
    "CutCheck",
    "DeckTalkError",
    "DoctorResult",
    "Edit",
    "EditFix",
    "ErrorCode",
    "ErrorInfo",
    "ErrorResult",
    "Event",
    "Events",
    "Fetch",
    "Finding",
    "FindingEvent",
    "Fix",
    "FixOutcome",
    "InitResult",
    "InputError",
    "InstallResult",
    "InstalledTool",
    "JsonlSink",
    "Layer",
    "Level",
    "Line",
    "LiveRun",
    "Location",
    "Log",
    "Loudness",
    "NarrateResult",
    "NotBuiltError",
    "Outcome",
    "PIPELINE",
    "Panel",
    "Progress",
    "ProjectLocked",
    "ProviderError",
    "RaisedBy",
    "RecordResult",
    "RenderedSection",
    "Result",
    "RunDone",
    "RunStart",
    "Scope",
    "SeamCheck",
    "SectionCues",
    "SectionDone",
    "SectionKind",
    "SectionRecording",
    "SectionStart",
    "SectionStatus",
    "SectionTake",
    "SectionWords",
    "ServeResult",
    "SettingFix",
    "SettingValue",
    "SkipReason",
    "SoundItem",
    "SoundKind",
    "SoundStatus",
    "SoundscapeResult",
    "Spend",
    "SpendEvent",
    "SpendState",
    "Stage",
    "StageDone",
    "StageRun",
    "StageSpec",
    "StageStart",
    "StartCheck",
    "StatusResult",
    "StoryboardResult",
    "Subscription",
    "Substitute",
    "TakeStatus",
    "ToolError",
    "Unit",
    "VerifyResult",
    "Voicing",
    "Word",
    "WordsResult",
    "__version__",
]
