"""The page contract as Python reads it: every attribute, every page code and every query key.

Generated by `scripts/build_runtime.py` from `src/decktalk/runtime/src/contract.ts`. Do not edit
this file, edit the contract and run the script.

An element on a slide has four moments and one value type. It arrives, it steps back, it comes to
the front, and it leaves, and each of those names a cue local to its slide, which `wire_id` joins
into the id `cues.json` carries. Everything else is either how a moment looks, which is a closed
word, or what a moment means, which is a sentence for the transcript.

This module is vocabulary and arithmetic and nothing else. It opens no file, reads no settings and
imports nothing from DeckTalk, so every layer above it may read the contract without a browser and
without a project.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict

__all__ = [
    "APPEAR_WORDS_MAX",
    "ATTENTION",
    "ATTRS",
    "Affects",
    "Attr",
    "AttrSpec",
    "BACK_OPACITY",
    "CAPTURE_FPS",
    "COUNTS",
    "ENTRANCES",
    "EXEMPT",
    "EXITS",
    "Effect",
    "FRAME_STEP_MS",
    "Kind",
    "MEASURABLE_SPAN_SECONDS",
    "MOMENTS",
    "ONSET_FIRST_FRAME_PERCENT",
    "PAIR_MARK",
    "PAIR_SEPARATOR",
    "PageWarning",
    "Q",
    "QUERY",
    "REPORT",
    "RaisedBy",
    "Range",
    "SLIDE_ENTRANCES",
    "Subject",
    "WIRE_MARK",
    "WORD_STYLES",
    "measurable",
    "scaled",
    "stagger_span",
    "wire_id",
]

CAPTURE_FPS = 25
"""The rate the recorder captures at, which is the rate Chromium paints a deck at."""

FRAME_STEP_MS = 40
"""One captured frame in milliseconds, which is the finest interval any page range may name."""

MEASURABLE_SPAN_SECONDS = 0.5
"""The longest motion a cue may still be playing, which is the unmeasurable threshold, the
reduced-motion clamp and the stagger ceiling in one number."""

ONSET_FIRST_FRAME_PERCENT = 25
"""The share of an entrance that must be drawn in its first captured frame."""

APPEAR_WORDS_MAX = 8
"""The words `appear` may reveal one at a time before the line is longer than a cue can carry."""

BACK_OPACITY = 0.45
"""The opacity a stepped-back element holds, which reads as secondary and stays readable."""

PAIR_SEPARATOR = "|"
"""What separates two moment pairs in one attribute value."""

PAIR_MARK = ":"
"""What separates a pair's moment from its value."""

WIRE_MARK = ":"
"""What joins a slide id to a local moment name in the id `cues.json` carries."""


class Subject(Enum):
    """What an attribute is written on. A container is an element whose children carry moments."""

    CONTAINER = "container"
    ELEMENT = "element"
    SCENE = "scene"
    SLIDE = "slide"


class Kind(Enum):
    """What kind of value an attribute takes, which is what a reader parses it as."""

    FLAG = "flag"
    ID = "id"
    MOMENT = "moment"
    NAMES = "names"
    PAIRS = "pairs"
    PHRASE = "phrase"
    SECONDS = "seconds"
    TEX = "tex"
    WORD = "word"


class Affects(Enum):
    """What turning an attribute changes, published so an agent can tell a knob from a label."""

    CATALOG = "catalog"
    CUE_ORDER = "cue-order"
    MOTION = "motion"
    PREVIEW = "preview"
    STYLE = "style"
    TRANSCRIPT = "transcript"


class RaisedBy(Enum):
    """Who raises a code. The runtime reports it from the page, and Python measures it after."""

    PYTHON = "python"
    RUNTIME = "runtime"


class Attr(Enum):
    """Every attribute name the contract defines. The value is the attribute as an author writes it."""

    IN = "data-in"
    DESCRIBE = "data-describe"
    TEX = "data-tex"
    TEX_DISPLAY = "data-tex-display"
    IN_STYLE = "data-in-style"
    BACK = "data-back"
    FRONT = "data-front"
    OUT = "data-out"
    WORDS = "data-words"
    COUNT = "data-count"
    CLASS = "data-class"
    DESCRIBE_CLASS = "data-describe-class"
    STAGGER = "data-stagger"
    STEPS = "data-steps"
    IN_SECONDS = "data-in-seconds"
    OUT_STYLE = "data-out-style"
    SWAPS = "data-swaps"
    DESCRIBE_OUT = "data-describe-out"
    SCENE = "data-scene"
    NAME = "data-name"
    SLIDE = "data-slide"
    HOLD = "data-hold"
    OWNS = "data-owns"
    ENTER = "data-enter"


class Q(Enum):
    """Every query key a DeckTalk page reads, which is the whole vocabulary of a page URL."""

    SCENE = "scene"
    SLIDE = "slide"
    CUES = "cues"
    WORDS = "words"
    T0 = "t0"
    SPEED = "speed"
    HUD = "hud"
    AFTER = "after"
    BEFORE = "before"


class PageWarning(Enum):
    """One code whose subject is the page. `name` is the code, and `message` is the sentence it prints.

    The message is a whole sentence carrying its own fix, written for the console and for a person.
    Nothing parses it, and the documentation URL is derived from the code by whoever prints it.
    """

    message: str
    certain: bool
    raised_by: RaisedBy

    def __init__(self, message: str, certain: bool, raised_by: RaisedBy) -> None:
        self.message = message
        self.certain = certain
        self.raised_by = raised_by

    def __repr__(self) -> str:
        return f"{type(self).__name__}.{self.name}"

    PAGE_UNKNOWN_ATTR = (
        ("{attr} is not an attribute this contract defines, so check its spelling against the attribute table."),
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_BAD_VALUE = (
        "{attr}={value} is not one of {allowed}, so write one of those instead.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_MOMENT_UNKNOWN = (
        ("{attr}={value} names a cue slide {slide} does not own, so declare it on the slide or correct the name."),
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_MOMENT_ORDER = (
        "The exit {value} is at or before the entrance on the same element, so give the exit a later cue.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_CUE_UNKNOWN = (
        "The cue {cue} is not one this deck declares, so remove it or name it in a moment attribute.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_NO_OWNER = (
        "No slide owns the cue {cue}, so name it in a moment attribute or list it in data-owns.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_SCENE_EMPTY = (
        "The scene {slide} declares no slide, so add a template to it or remove the scene.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_SLIDE_NO_ID = (
        "A template carries no data-slide, so give it the id a section names.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_SLIDE_DOUBLED = (
        "Two templates claim the slide id {slide}, so every moment local to it has two owners.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_SLIDE_UNUSED = (
        "Slide {slide} is never shown, so nothing it declares reaches a recording.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_TEMPLATE_IGNORED = (
        "A template inside slide {slide} declares no slide of its own, so nothing ever mounts it.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_WORDS_NOT_FOUND = (
        "The line {value} is not among the spoken words, so it cannot be shown word by word.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_KATEX_MISSING = (
        "KaTeX is not loaded, so {attr} is left as the author wrote it.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_KATEX_ERROR = (
        "KaTeX refused {value}, so the element shows its readable fallback text.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_FREEZE_CUE_UNKNOWN = (
        "The cue {cue} is not one of slide {slide}'s cues, so the freeze stopped at nothing.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_RENDER_THREW = (
        "The render handler for slide {slide} threw {value}, so the slide is drawn as its markup stands.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_ENTER_THREW = (
        "The enter handler for slide {slide} threw {value}, so the slide arrived without it.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_SLIDE_HANDLER_THREW = (
        "The handler slide {slide} registered for cue {cue} threw {value}, so that moment did nothing.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_HANDLER_THREW = (
        "The handler the deck registered for cue {cue} threw {value}, so that moment did nothing.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_WAIT_REJECTED = (
        "A promise the page waited for rejected with {value}, so the page was drawn without it.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_WAIT_UNSETTLED = (
        "A promise the page waited for never settled, so the page was drawn without it.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_CLASS_UNDESCRIBED = (
        "data-class names {value} with no phrase for it in data-describe-class, so the transcript loses it.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_CLASS_NOT_REDUCED = (
        ("The class {value} still animates under reduced motion, so the page's own stylesheet must honour it."),
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_SWAP_AMBIGUOUS = (
        ("data-swaps at cue {cue} found {value} elements leaving, so name the one it replaces with a shared cue."),
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_PREVIEW_AMBIGUOUS = (
        "Two sections name the scene {slide}, so a preview cannot tell which one's cue times to play.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_APPEAR_TOO_LONG = (
        "data-words=appear is on a line of {value} words, so shorten it or use highlight instead.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_STAGGER_EMPTY = (
        "The container at cue {cue} staggers no children, so give it children or remove the attribute.",
        True,
        RaisedBy.RUNTIME,
    )
    PAGE_MOTION_OVERRUN = (
        "The motion at cue {cue} is still playing {value} s later, at the frame the next cue is read from.",
        True,
        RaisedBy.PYTHON,
    )
    PAGE_STAGGER_OVERRUN = (
        "The stagger at cue {cue} runs {value} s in all, which passes the half second a cue may still move.",
        True,
        RaisedBy.PYTHON,
    )
    PAGE_WORD_LATE = (
        ("The first synced word of {value} was shown after the voice reached it, so the line trails the speech."),
        True,
        RaisedBy.PYTHON,
    )
    PAGE_THIN_DRAW = (
        "The stroke at cue {cue} sweeps {value} percent of the frame, which is under the change floor.",
        False,
        RaisedBy.PYTHON,
    )
    PAGE_NO_DESCRIPTION = (
        "The element at cue {cue} has no text and no data-tex, so give it data-describe or an empty one.",
        True,
        RaisedBy.PYTHON,
    )
    PAGE_SWAP_APART = (
        ("The swap at cue {cue} lands {value} percent over the box it replaces, so the two may read as unrelated."),
        False,
        RaisedBy.PYTHON,
    )
    PAGE_STALLED = (
        ("The page stopped drawing {value} s into the recording, so every later cue was captured on a dead frame."),
        True,
        RaisedBy.PYTHON,
    )
    PAGE_BLACK = (
        ("The frame at cue {cue} is black, so nothing the slide declares was on screen when the voice arrived."),
        True,
        RaisedBy.PYTHON,
    )
    PAGE_TRUNCATED = (
        "The recording ends {value} s before the narration does, so the last cues are not in it.",
        True,
        RaisedBy.PYTHON,
    )
    PAGE_CDN_ASSET = (
        "The page loaded {value} from another origin, so the film depends on a host it does not own.",
        True,
        RaisedBy.PYTHON,
    )


class Frozen(BaseModel):
    """A published record of the contract, which nothing may edit after the module is imported."""

    model_config = ConfigDict(frozen=True, extra="forbid")


class Range(Frozen):
    """The values a number attribute admits, in the unit the tool can see."""

    min: float
    max: float
    step: float
    unit: str


class Effect(Frozen):
    """One closed word of a style set, with the motion it puts between its cue and the next one."""

    seconds: float
    lift_pixels: int = 0
    overshoot_percent: float = 0


class AttrSpec(Frozen):
    """One row of the attribute table, which is everything published about one knob.

    `span` is the seconds of motion the row puts between its cue and the next one. A number is the
    span the row declares on its own, zero is a row that never moves a pixel, and `None` is a row
    whose span is read from the page or from a closed word set. Every span is bounded by
    `MEASURABLE_SPAN_SECONDS`, whichever of the three it is.
    """

    name: Attr
    on: tuple[Subject, ...]
    kind: Kind
    values: tuple[str, ...]
    default: str | None
    range: Range | None
    code: PageWarning | None
    span: float | None
    affects: tuple[Affects, ...]
    summary: str


ENTRANCES: dict[str, Effect] = {
    "rise": Effect(seconds=0.32, lift_pixels=10, overshoot_percent=0),
    "settle": Effect(seconds=0.28, lift_pixels=4, overshoot_percent=0),
    "fade": Effect(seconds=0.24, lift_pixels=0, overshoot_percent=0),
    "pop": Effect(seconds=0.2, lift_pixels=0, overshoot_percent=4),
    "draw": Effect(seconds=0.48, lift_pixels=0, overshoot_percent=0),
    "cut": Effect(seconds=0, lift_pixels=0, overshoot_percent=0),
}
"""How long each entrance plays and how far outside its resting box it travels."""

EXITS: dict[str, Effect] = {
    "fade": Effect(seconds=0.2),
    "fall": Effect(seconds=0.2),
}
"""How long each exit plays."""

SLIDE_ENTRANCES: dict[str, Effect] = {
    "crossfade": Effect(seconds=0.24),
    "cut": Effect(seconds=0),
}
"""How a slide replaces the one before it, and how long that takes."""

WORD_STYLES: dict[str, Effect] = {
    "highlight": Effect(seconds=0.12),
    "appear": Effect(seconds=0.12),
}
"""How a line is shown on the voice, and how long one word takes to arrive."""

COUNTS: dict[str, Effect] = {
    "last": Effect(seconds=0.48),
    "first": Effect(seconds=0.48),
}
"""Which number in the text counts up from zero, and how long the count runs."""

ATTENTION: dict[str, Effect] = {
    "back": Effect(seconds=0.28),
    "front": Effect(seconds=0.2),
}
"""How long a step back and a return to the front play."""

ATTRS: dict[Attr, AttrSpec] = {
    Attr.IN: AttrSpec(
        name=Attr.IN,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.MOMENT,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_MOMENT_UNKNOWN,
        span=None,
        affects=(
            Affects.CUE_ORDER,
            Affects.MOTION,
            Affects.TRANSCRIPT,
            Affects.CATALOG,
        ),
        summary="The element arrives at this cue.",
    ),
    Attr.DESCRIBE: AttrSpec(
        name=Attr.DESCRIBE,
        on=(
            Subject.ELEMENT,
            Subject.SLIDE,
        ),
        kind=Kind.PHRASE,
        values=(),
        default=None,
        range=None,
        code=None,
        span=0,
        affects=(
            Affects.TRANSCRIPT,
            Affects.CATALOG,
        ),
        summary=(
            "The subject of the reveal, which the runtime gives a verb per moment. An empty phrase means decorative."
        ),
    ),
    Attr.TEX: AttrSpec(
        name=Attr.TEX,
        on=(Subject.ELEMENT,),
        kind=Kind.TEX,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_KATEX_ERROR,
        span=0,
        affects=(
            Affects.CATALOG,
            Affects.TRANSCRIPT,
        ),
        summary="Typeset with KaTeX, with the element's own text as the readable fallback.",
    ),
    Attr.TEX_DISPLAY: AttrSpec(
        name=Attr.TEX_DISPLAY,
        on=(Subject.ELEMENT,),
        kind=Kind.FLAG,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_KATEX_ERROR,
        span=0,
        affects=(
            Affects.CATALOG,
            Affects.STYLE,
        ),
        summary="Typeset the TeX as a display equation on its own line rather than inline.",
    ),
    Attr.IN_STYLE: AttrSpec(
        name=Attr.IN_STYLE,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.WORD,
        values=("rise", "settle", "fade", "pop", "draw", "cut"),
        default="rise",
        range=None,
        code=PageWarning.PAGE_BAD_VALUE,
        span=None,
        affects=(
            Affects.MOTION,
            Affects.STYLE,
        ),
        summary="How the element arrives. Each word declares its own span.",
    ),
    Attr.BACK: AttrSpec(
        name=Attr.BACK,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.MOMENT,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_MOMENT_UNKNOWN,
        span=0.28,
        affects=(
            Affects.CUE_ORDER,
            Affects.MOTION,
            Affects.TRANSCRIPT,
            Affects.CATALOG,
        ),
        summary="The element steps back at this cue, dimmed but still readable.",
    ),
    Attr.FRONT: AttrSpec(
        name=Attr.FRONT,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.MOMENT,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_MOMENT_UNKNOWN,
        span=0.2,
        affects=(
            Affects.CUE_ORDER,
            Affects.MOTION,
            Affects.TRANSCRIPT,
            Affects.CATALOG,
        ),
        summary="The element returns to full strength at this cue.",
    ),
    Attr.OUT: AttrSpec(
        name=Attr.OUT,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.MOMENT,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_MOMENT_ORDER,
        span=None,
        affects=(
            Affects.CUE_ORDER,
            Affects.MOTION,
            Affects.TRANSCRIPT,
            Affects.CATALOG,
        ),
        summary="The element leaves at this cue.",
    ),
    Attr.WORDS: AttrSpec(
        name=Attr.WORDS,
        on=(Subject.ELEMENT,),
        kind=Kind.WORD,
        values=("highlight", "appear"),
        default="highlight",
        range=None,
        code=PageWarning.PAGE_WORDS_NOT_FOUND,
        span=0.12,
        affects=(
            Affects.MOTION,
            Affects.STYLE,
        ),
        summary="The line is shown word by word on the voice, matched against the section's spoken words.",
    ),
    Attr.COUNT: AttrSpec(
        name=Attr.COUNT,
        on=(Subject.ELEMENT,),
        kind=Kind.WORD,
        values=("last", "first"),
        default=None,
        range=None,
        code=PageWarning.PAGE_BAD_VALUE,
        span=0.48,
        affects=(
            Affects.MOTION,
            Affects.STYLE,
        ),
        summary="A number in the text counts up from zero when the element arrives.",
    ),
    Attr.CLASS: AttrSpec(
        name=Attr.CLASS,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.PAIRS,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_CLASS_UNDESCRIBED,
        span=None,
        affects=(
            Affects.CUE_ORDER,
            Affects.MOTION,
            Affects.TRANSCRIPT,
            Affects.STYLE,
        ),
        summary="Adds a class at a moment, written as moment:name pairs, for the page's own stylesheet.",
    ),
    Attr.DESCRIBE_CLASS: AttrSpec(
        name=Attr.DESCRIBE_CLASS,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.PAIRS,
        values=(),
        default=None,
        range=None,
        code=None,
        span=0,
        affects=(Affects.TRANSCRIPT,),
        summary="What each class change means, as moment:phrase pairs separated by a vertical bar.",
    ),
    Attr.STAGGER: AttrSpec(
        name=Attr.STAGGER,
        on=(Subject.CONTAINER,),
        kind=Kind.SECONDS,
        values=(),
        default=None,
        range=Range(min=0.04, max=0.2, step=0.04, unit="seconds"),
        code=PageWarning.PAGE_STAGGER_OVERRUN,
        span=None,
        affects=(Affects.MOTION,),
        summary="The container's children arrive this far apart from one cue.",
    ),
    Attr.STEPS: AttrSpec(
        name=Attr.STEPS,
        on=(Subject.CONTAINER,),
        kind=Kind.FLAG,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_STAGGER_EMPTY,
        span=None,
        affects=(
            Affects.CUE_ORDER,
            Affects.MOTION,
            Affects.TRANSCRIPT,
            Affects.CATALOG,
        ),
        summary="Each cued child comes to the front as it arrives and the ones before it step back.",
    ),
    Attr.IN_SECONDS: AttrSpec(
        name=Attr.IN_SECONDS,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.SECONDS,
        values=(),
        default=None,
        range=Range(min=0.12, max=0.48, step=0.04, unit="seconds"),
        code=PageWarning.PAGE_BAD_VALUE,
        span=None,
        affects=(Affects.MOTION,),
        summary="How long the entrance plays, which governs the entrance alone and never the onset.",
    ),
    Attr.OUT_STYLE: AttrSpec(
        name=Attr.OUT_STYLE,
        on=(
            Subject.ELEMENT,
            Subject.CONTAINER,
        ),
        kind=Kind.WORD,
        values=("fade", "fall"),
        default="fade",
        range=None,
        code=PageWarning.PAGE_BAD_VALUE,
        span=0.2,
        affects=(
            Affects.MOTION,
            Affects.STYLE,
        ),
        summary="How the element leaves.",
    ),
    Attr.SWAPS: AttrSpec(
        name=Attr.SWAPS,
        on=(Subject.ELEMENT,),
        kind=Kind.FLAG,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_SWAP_AMBIGUOUS,
        span=None,
        affects=(
            Affects.MOTION,
            Affects.CATALOG,
        ),
        summary="The element takes the place of whatever leaves on its own arrival cue, in a held swap.",
    ),
    Attr.DESCRIBE_OUT: AttrSpec(
        name=Attr.DESCRIBE_OUT,
        on=(Subject.ELEMENT,),
        kind=Kind.PHRASE,
        values=(),
        default=None,
        range=None,
        code=None,
        span=0,
        affects=(Affects.TRANSCRIPT,),
        summary="Overrides the departure sentence when leaving means something of its own.",
    ),
    Attr.SCENE: AttrSpec(
        name=Attr.SCENE,
        on=(Subject.SCENE,),
        kind=Kind.ID,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_SCENE_EMPTY,
        span=0,
        affects=(Affects.CATALOG,),
        summary="Declares the scene a section names, on the wrapper that holds its slides.",
    ),
    Attr.NAME: AttrSpec(
        name=Attr.NAME,
        on=(Subject.SCENE,),
        kind=Kind.PHRASE,
        values=(),
        default=None,
        range=None,
        code=None,
        span=0,
        affects=(Affects.CATALOG,),
        summary="The scene's name in the index and in the catalog.",
    ),
    Attr.SLIDE: AttrSpec(
        name=Attr.SLIDE,
        on=(Subject.SLIDE,),
        kind=Kind.ID,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_SLIDE_NO_ID,
        span=0,
        affects=(
            Affects.CUE_ORDER,
            Affects.CATALOG,
        ),
        summary="Declares a slide on a template. Its id qualifies every moment written inside it.",
    ),
    Attr.HOLD: AttrSpec(
        name=Attr.HOLD,
        on=(Subject.SLIDE,),
        kind=Kind.SECONDS,
        values=(),
        default="8",
        range=Range(min=1, max=60, step=1, unit="seconds"),
        code=None,
        span=0,
        affects=(Affects.PREVIEW,),
        summary="How long the preview rests on this slide. No recording reads it.",
    ),
    Attr.OWNS: AttrSpec(
        name=Attr.OWNS,
        on=(Subject.SLIDE,),
        kind=Kind.NAMES,
        values=(),
        default=None,
        range=None,
        code=PageWarning.PAGE_CUE_UNKNOWN,
        span=0,
        affects=(
            Affects.CUE_ORDER,
            Affects.CATALOG,
        ),
        summary="Local names of cues only a handler serves, which no moment attribute mentions.",
    ),
    Attr.ENTER: AttrSpec(
        name=Attr.ENTER,
        on=(Subject.SLIDE,),
        kind=Kind.WORD,
        values=("crossfade", "cut"),
        default="crossfade",
        range=None,
        code=PageWarning.PAGE_BAD_VALUE,
        span=0.24,
        affects=(
            Affects.MOTION,
            Affects.STYLE,
        ),
        summary="How this slide replaces the one before it.",
    ),
}
"""Every attribute of the contract, in the order an author reaches for them."""

EXEMPT = {
    Attr.DESCRIBE: "Any phrase clears the finding, so no value of it can change a verdict.",
    Attr.DESCRIBE_CLASS: "The transcript prints the phrase verbatim, so no value of it can change a verdict.",
    Attr.DESCRIBE_OUT: "It replaces one transcript sentence with another, and neither is measured.",
    Attr.HOLD: "The preview alone reads it, and a preview is never recorded.",
    Attr.NAME: "It names a scene in the index, which no check and no finding reads.",
}
"""The rows that survive without a code, and the sentence that says why each one is allowed to."""

QUERY = {
    Q.SCENE: "Play this scene from its first slide.",
    Q.SLIDE: "Freeze this slide with its cues already fired, which is what a screenshot opens.",
    Q.CUES: "The cue times to fire at, as id@seconds pairs separated by a comma.",
    Q.WORDS: "The spoken words to sync a line against, as word@seconds pairs separated by a comma.",
    Q.T0: "The narration second the page starts at, or the word signal when the recorder starts the clock.",
    Q.SPEED: "Multiply the preview clock, so a long section is reviewed quickly.",
    Q.HUD: "Draw the on-page clock and cue list, which is for an author and never for a recording.",
    Q.AFTER: "Freeze after this cue, so the cues up to and including it fire and later ones stay hidden.",
    Q.BEFORE: "Freeze just before this cue, so it and every later cue stay hidden.",
}
"""What each query key asks the page for."""

REPORT = {
    "version": "The runtime version the page carries.",
    "mode": "Which of index, preview, cue and freeze the page is in.",
    "scene": "The scene the page is playing, or null on the index page.",
    "slide": "The slide on screen, or null when none is mounted.",
    "warnings": "Every distinct warning the page reported, as code, message, slide, cue and attr.",
    "catalog": "One entry per scene, with its slides, its cues and the measured box of every element.",
    "cues": "When each cue was due, when it ran, and when the frames around it began.",
    "words": "Each synced line, when its cue ran, when the voice reaches it and when its first word showed.",
    "frameGaps": "Every gap between two animation frames longer than the recorder can absorb.",
    "longFrames": "Every animation frame that took longer than a captured frame, with when it was presented.",
}
"""Every field the probe's one report call answers with, and what a reader does with it."""

MOMENTS: tuple[Attr, ...] = (
    Attr.IN,
    Attr.BACK,
    Attr.FRONT,
    Attr.OUT,
)
"""Every attribute whose value is the local name of a cue, which is what joins the cue order."""


def wire_id(slide: str, local: str) -> str:
    """The id `cues.json` carries for a moment, which is the slide it was written in and its local name."""
    return f"{slide}{WIRE_MARK}{local}"


def stagger_span(step: float, children: int, entrance: float) -> float:
    """The whole span a staggered container puts between its cue and the next one.

    The arithmetic is exact, which is why `PAGE_STAGGER_OVERRUN` is certain: the last child starts
    one step per earlier child after the cue and then plays its own entrance.
    """
    return step * (children - 1) + entrance if children > 0 else 0.0


def measurable(span: float) -> bool:
    """Whether a declared span is short enough for the cue it belongs to still to be measurable."""
    return span < MEASURABLE_SPAN_SECONDS


def scaled(span: float, scale: float) -> float:
    """A declared span under a reduced-motion render, clamped so no scaled span crosses the ceiling.

    The scale multiplies the declared span as well as the duration, so a project that slows its
    motion down cannot slow it past the point where its own cues stop being measurable.
    """
    return min(span * scale, MEASURABLE_SPAN_SECONDS - FRAME_STEP_MS / 1000)
