"""The public Python API is a root of about thirty names and six public modules, and it is closed.

`src/decktalk/__init__.py` is generated by `scripts/build_api.py` from the root names that script
lists. The public modules are `decktalk.results`, `decktalk.events`, `decktalk.findings`,
`decktalk.settings`, `decktalk.speech` and `decktalk.speech.sound`, and each one's `__all__` is its
public surface. Everything else in the package is internal and may move without notice.

The rule this file holds is closure: a type a public name can hand a caller, or ask a caller for, is
a type the caller can import from the root or from a public module. It is read off the imported
package, and it walks every public method's signature as well as every field, because a method that
takes or returns an internal type leaks it exactly as a field does. Each parameter and each return
annotation is resolved, so a forward reference is checked as the class it names.
"""

from __future__ import annotations

import ast
import enum
import importlib
import inspect
import types
import typing
from collections.abc import Iterator
from typing import TypeAliasType, TypeGuard, get_args, get_origin

import pytest
from pydantic import BaseModel

import decktalk
from decktalk.results import RESULTS
from support.paths import SRC

PACKAGE = "decktalk"

PUBLIC_MODULES = ("results", "events", "findings", "settings", "speech", "speech.sound")
"""The modules whose `__all__` is public beside the root, which is everything a caller may import."""

ROOT_LIMIT = 32
"""The most names the root may carry, which keeps it the short list of entry points a newcomer reads."""

NOT_PUBLIC = ("catalog", "Catalog")
"""Names kept out of every public surface, because `decktalk schema` composes its walkers internally."""

EXPORTED = tuple(decktalk.__all__)


def public() -> dict[str, object]:
    """Every public name, from the root and from each public module, by where a caller imports it."""
    found: dict[str, object] = {f"decktalk.{name}": getattr(decktalk, name) for name in EXPORTED}
    for module_name in PUBLIC_MODULES:
        module = importlib.import_module(f"{PACKAGE}.{module_name}")
        found |= {f"decktalk.{module_name}.{name}": getattr(module, name) for name in getattr(module, "__all__", ())}
    return found


PUBLIC = public()
PUBLIC_IDS = {id(obj) for obj in PUBLIC.values()}


def declaring() -> list[str]:
    """Every module of the package whose own source assigns `__all__` at the top level, by dotted name."""
    found = []
    for path in sorted(SRC.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        targets = [
            target
            for node in tree.body
            if isinstance(node, ast.Assign | ast.AnnAssign)
            for target in (node.targets if isinstance(node, ast.Assign) else [node.target])
        ]
        if any(isinstance(target, ast.Name) and target.id == "__all__" for target in targets):
            parts = path.relative_to(SRC.parent).with_suffix("").parts
            found.append(".".join(parts[:-1] if parts[-1] == "__init__" else parts))
    return found


def owned(obj: object) -> TypeGuard[type]:
    """Whether a class is one this package defines, which is what the closure has to reach."""
    return inspect.isclass(obj) and getattr(obj, "__module__", "").split(".")[0] == PACKAGE


def reachable(annotation: object) -> list[object]:
    """Every class or alias this package owns that is named anywhere inside one annotation."""
    if owned(annotation):
        return [annotation]
    if isinstance(annotation, list | tuple):
        # The parameters of a `Callable[[A, B], R]` arrive as one list among its arguments.
        return [one for argument in annotation for one in reachable(argument)]
    if isinstance(annotation, TypeAliasType):
        mine = getattr(annotation, "__module__", "").split(".")[0] == PACKAGE
        return [annotation] if mine else reachable(annotation.__value__)
    if get_origin(annotation) is None and not isinstance(annotation, types.UnionType):
        return []
    found = reachable(get_origin(annotation)) if isinstance(get_origin(annotation), TypeAliasType) else []
    return found + [one for argument in get_args(annotation) for one in reachable(argument)]


def hints(function: object, owner: type | None = None) -> dict[str, object]:
    """One callable's parameter and return annotations, resolved, or a failure that names it.

    The type parameters of the callable and of the class that owns it are passed as the local
    names, because `get_type_hints` before Python 3.12.4 resolves a string annotation from the
    module alone, where a parameter such as `E` in `def emit[E: Event]` is not defined.
    """
    scopes = (owner, function)
    params = {param.__name__: param for scope in scopes for param in getattr(scope, "__type_params__", ())}
    try:
        return typing.get_type_hints(function, localns=params or None)
    except NameError as missing:  # pragma: no cover - the failure message is the test's output
        pytest.fail(f"{getattr(function, '__qualname__', function)} names a type nothing can resolve: {missing}")


def callables_of(cls: type) -> Iterator[tuple[str, object]]:
    """Every public method, property, class method and constructor a class this package owns defines."""
    seen: set[str] = set()
    for base in cls.__mro__:
        if not owned(base) or issubclass(base, enum.Enum):
            continue
        for name, member in vars(base).items():
            if name in seen or (name.startswith("_") and name not in {"__init__", "__call__"}):
                continue
            seen.add(name)
            if isinstance(member, property):
                if member.fget is not None:
                    yield name, member.fget
            elif isinstance(member, classmethod | staticmethod):
                yield name, member.__func__
            elif inspect.isfunction(member):
                yield name, member


def fields_of(cls: type) -> Iterator[tuple[str, object]]:
    """Every public field a class this package owns declares, a model's or a plain class's."""
    if issubclass(cls, BaseModel):
        for name, field in cls.model_fields.items():
            yield f".{name}", field.annotation
        return
    for name, annotation in hints(cls).items():
        if not name.startswith("_"):
            yield f".{name}", annotation


def annotations_of(obj: object) -> Iterator[tuple[str, object]]:
    """Every annotation one public name publishes: its fields, every public signature, or an alias's value."""
    if isinstance(obj, TypeAliasType):
        yield "", obj.__value__
    elif inspect.isroutine(obj):
        for parameter, annotation in hints(obj).items():
            yield f"({parameter})", annotation
    elif inspect.isclass(obj) and not issubclass(obj, enum.Enum):
        yield from fields_of(obj)
        for name, member in callables_of(obj):
            for parameter, annotation in hints(member, obj).items():
                yield f".{name}({parameter})", annotation


def leaks(name: str) -> list[str]:
    """Every internal type one public name hands out or asks for, each with where it appears."""
    return sorted(
        f"{name}{where} names {found.__module__}.{getattr(found, '__name__', found)}"
        for where, annotation in annotations_of(PUBLIC[name])
        for found in reachable(annotation)
        if id(found) not in PUBLIC_IDS
    )


def test_the_root_is_a_short_list_of_entry_points():
    """The root carries the entry points and the errors, and every row and event lives in its own module."""
    assert len(EXPORTED) <= ROOT_LIMIT, sorted(EXPORTED)


@pytest.mark.parametrize("name", EXPORTED)
def test_every_root_name_resolves_and_is_public(name: str):
    """A name in `__all__` that nothing answers is a promise the package cannot keep."""
    assert hasattr(decktalk, name), name
    assert not name.startswith("_") or name == "__version__", name


@pytest.mark.parametrize("module_name", PUBLIC_MODULES)
def test_every_public_module_declares_its_surface(module_name: str):
    """A public module says what it publishes, and every name it lists is one it holds."""
    module = importlib.import_module(f"{PACKAGE}.{module_name}")
    assert getattr(module, "__all__", ()), module_name
    assert [name for name in module.__all__ if not hasattr(module, name)] == []


def test_every_module_holds_every_name_its_all_lists():
    """`from module import *` reads `__all__`, so a listed name the module does not hold fails that import."""
    modules = [importlib.import_module(module_name) for module_name in declaring()]
    missing = [
        f"{module.__name__}.{name}" for module in modules for name in module.__all__ if not hasattr(module, name)
    ]
    assert missing == [], missing


@pytest.mark.parametrize("name", sorted(PUBLIC))
def test_every_public_signature_names_only_public_types(name: str):
    """The closure rule, over fields and over every public method's parameters and return.

    A type a caller can receive or must pass, and cannot import from a public module, is a surface
    a caller cannot name, so it fails here whether a field or a method signature names it.
    """
    assert leaks(name) == [], "Make each type public in a public module's __all__, or make the member private."


def test_every_result_class_is_public():
    """`RESULTS` is what `decktalk schema NAME` renders, so every one of them is importable."""
    missing = sorted({model.__name__ for model in RESULTS.values()} - set(decktalk.results.__all__))
    assert missing == [], missing


@pytest.mark.parametrize("name", NOT_PUBLIC)
def test_the_names_kept_internal_are_not_public(name: str):
    assert all(not key.endswith(f".{name}") for key in PUBLIC), f"{name} is public, and only the schema uses it."


def test_no_public_enum_publishes_a_member_the_schema_cannot_name():
    """A closed vocabulary reaches a reader as its value, so every member has to carry one."""
    for name, obj in PUBLIC.items():
        if inspect.isclass(obj) and issubclass(obj, enum.Enum):
            for member in obj:
                assert member.value is not None, f"{name}.{member.name} has no value to publish."


def test_the_walk_reads_method_signatures_and_not_only_fields():
    """The walk is what holds the rule, so it is shown to catch a method that hands out an internal type."""

    class Internal:
        pass

    Internal.__module__ = f"{PACKAGE}.stages"

    class Exposed:
        def make(self) -> object:
            return Internal()

    Exposed.make.__annotations__ = {"return": Internal}
    Exposed.__module__ = f"{PACKAGE}.results"
    walked = [found for _, annotation in annotations_of(Exposed) for found in reachable(annotation)]
    assert walked == [Internal]


def test_the_package_opens_a_project_and_names_the_version():
    """The two facts every caller starts from: a project is opened by path, and the package says its version."""
    assert callable(decktalk.open)
    assert typing.get_type_hints(decktalk.open)["return"] is decktalk.Project
    assert isinstance(decktalk.__version__, str) and decktalk.__version__
