"""`decktalk.__all__` is the whole supported Python API, and it is a closure rather than a list.

`src/decktalk/__init__.py` is generated by `scripts/build_api.py`, which starts from the modules that
declare a public surface and adds every type reachable from what they export. This file holds the
rule that generator implements, read off the imported package rather than off the file, because a
name an agent meets in a JSON Schema and cannot import is a surface that fails the founder's thesis.

The rule that used to stand here, that the package docstring names every exported name, is deleted.
With `__all__` at the reachable closure the docstring would be a table of contents nobody reads, and
the closure test below proves what that rule was standing in for.
"""

from __future__ import annotations

import enum
import inspect
import types
import typing
from typing import get_args, get_origin

import pytest
from pydantic import BaseModel

import decktalk
from decktalk.results import RESULTS, Result

PACKAGE = "decktalk"

NOT_PUBLIC = ("catalog", "Catalog", "SpeechProvider", "SpeechRequest", "ProviderFactory")
"""Names the founder's decisions keep out of the surface: 12 for the catalog, 7 for the provider seam.

`decktalk schema` composes the walkers internally, so nothing named catalog is published, and
ElevenLabs is the only provider, so no provider type is importable.
"""

EXPORTED = tuple(decktalk.__all__)


def owned(obj: object) -> bool:
    """Whether a class is one this package defines, which is what the closure has to reach."""
    return inspect.isclass(obj) and getattr(obj, "__module__", "").split(".")[0] == PACKAGE


def reachable(annotation: object) -> list[type]:
    """Every class this package owns that is named anywhere inside one annotation."""
    if owned(annotation):
        return [annotation]
    if get_origin(annotation) is None and not isinstance(annotation, types.UnionType):
        return []
    return [found for argument in get_args(annotation) for found in reachable(argument)]


def annotations_of(obj: object) -> list[object]:
    """Every annotation one exported name publishes: a model's fields, or a callable's signature."""
    if inspect.isclass(obj) and issubclass(obj, BaseModel):
        return [field.annotation for field in obj.model_fields.values()]
    if inspect.isclass(obj):
        return [value for name, value in typing.get_type_hints(obj).items() if not name.startswith("_")]
    if callable(obj):
        try:
            hints = typing.get_type_hints(obj)
        except (NameError, TypeError):
            return []
        return list(hints.values())
    return []


def test_all_is_sorted_and_holds_each_name_once():
    assert list(EXPORTED) == sorted(EXPORTED)
    assert len(set(EXPORTED)) == len(EXPORTED)


@pytest.mark.parametrize("name", EXPORTED)
def test_every_exported_name_resolves_and_is_public(name: str):
    """A name in `__all__` that nothing answers is a promise the package cannot keep."""
    assert hasattr(decktalk, name), name
    assert not name.startswith("_") or name == "__version__", name


@pytest.mark.parametrize("name", EXPORTED)
def test_every_type_an_exported_name_publishes_is_exported_beside_it(name: str):
    """The closure rule: a type a caller can see in a payload and cannot import is undiscoverable."""
    obj = getattr(decktalk, name)
    missing = sorted(
        {found.__name__ for annotation in annotations_of(obj) for found in reachable(annotation)} - set(EXPORTED)
    )
    assert missing == [], f"{name} publishes {missing}. Run `uv run scripts/build_api.py --write`."


def test_every_result_class_is_exported():
    """`RESULTS` is what `decktalk schema NAME` renders, so every one of them is importable."""
    missing = sorted({model.__name__ for model in RESULTS.values()} - set(EXPORTED))
    assert missing == [], missing


@pytest.mark.parametrize("name", [name for name in EXPORTED if name[0].islower() and name != "__version__"])
def test_every_exported_call_that_returns_a_result_exports_that_result(name: str):
    """A call whose result a caller cannot name is a call a caller cannot type against."""
    obj = getattr(decktalk, name)
    if not callable(obj):
        return
    returned = typing.get_type_hints(obj).get("return")
    if inspect.isclass(returned) and issubclass(returned, Result):
        assert returned.__name__ in EXPORTED, f"{name} returns {returned.__name__}, which is not exported."


@pytest.mark.parametrize("name", NOT_PUBLIC)
def test_the_names_the_founder_kept_internal_are_not_exported(name: str):
    assert name not in EXPORTED, f"{name} is exported, against the founder's decision that keeps it internal."


def test_no_exported_enum_publishes_a_member_the_schema_cannot_name():
    """A closed vocabulary reaches a reader as its value, so every member has to carry one."""
    for name in EXPORTED:
        obj = getattr(decktalk, name)
        if inspect.isclass(obj) and issubclass(obj, enum.Enum):
            for member in obj:
                assert member.value is not None, f"{name}.{member.name} has no value to publish."


def test_the_package_opens_a_project_and_names_the_version():
    """The two facts every caller starts from: a project is opened by path, and the package says its version."""
    assert callable(decktalk.open)
    assert typing.get_type_hints(decktalk.open)["return"] is decktalk.Project
    assert isinstance(decktalk.__version__, str) and decktalk.__version__
