"""Generate the measured-numbers page and the README's measured block from docs/data/measured.json.

    uv run scripts/build_measured.py --write    # write the page and the block
    uv run scripts/build_measured.py --check    # exit 1 if either would change

`scripts/measure.py` runs the real commands on a real machine and writes the data file, and this
renders it. Every number on the page and in the README's block is read from that file, so neither
can say what no run measured, and a new measurement changes both by being written.

The prose around the tables lives in scripts/measured.mdx.j2, which reads as the page does. Each
landing row renders as its own row, so a measurement that adds a row to the file adds it to the page
without a change here.
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path
from typing import Any

import jinja2

import generated

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "data" / "measured.json"
PAGE = ROOT / "docs" / "reference" / "measured.mdx"
README = ROOT / "README.md"
TEMPLATE = ROOT / "scripts" / "measured.mdx.j2"

SCHEMA = 1
"""Truth: the shape version `scripts/measure.py` writes, and the only one this renders."""

PAGE_URL = "https://docs.decktalk.ai/reference/measured"
"""Where the README's block sends a reader for every number and how it was measured."""

MARKERS = ("<!-- measured: generated by scripts/build_measured.py -->", "<!-- end measured -->")

SHORT_COMMIT = 12
"""Calibration: twelve hex digits name a commit uniquely in any repository this size."""

FINE_BELOW_SECONDS = 1
"""Calibration: a time under a second is printed to the hundredth, since a tenth would round most of it away."""


def seconds(value: float) -> str:
    """A wall time as the page prints it, to the tenth of a second or the hundredth under one."""
    return f"{value:.2f} s" if value < FINE_BELOW_SECONDS else f"{value:.1f} s"


def ms(value: float) -> str:
    """A landing distance as the page prints it, in whole milliseconds."""
    return f"{round(value)} ms"


def recorded(counts: list[int], sections: int) -> str:
    """How many sections a build recorded, as one count or as the range the repeats spanned."""
    low, high = min(counts), max(counts)
    return f"{low} of {sections}" if low == high else f"{low} to {high} of {sections}"


def checked(data: dict[str, Any]) -> dict[str, Any]:
    """The data, refused when its shape is one this generator was not written for."""
    if data.get("schema") != SCHEMA:
        raise SystemExit(f"{SOURCE.name} has schema {data.get('schema')!r}, and this renders schema {SCHEMA} alone.")
    return data


def view(data: dict[str, Any]) -> dict[str, Any]:
    """Every value the page and the block print, formatted once from the data."""
    data = checked(data)
    builds = data["builds"]
    sections = builds["sections"]
    runs = {
        name: {
            **run,
            "commit": run["commit"][:SHORT_COMMIT],
        }
        for name, run in data["runs"].items()
    }
    landing = [
        {
            **row,
            "worst": ms(row["worst_ms"]),
            "median": ms(row["median_ms"]),
            "limit": ms(row["limit_ms"]),
            "per_cue": [
                {"cue": cue["cue"], "offsets": ", ".join(str(round(value)) for value in cue["offsets_ms"])}
                for cue in row["cues"]
            ],
        }
        for row in data["landing"]
    ]
    rows = [
        {
            "build": row["build"],
            "median": seconds(statistics.median(row["seconds"])),
            "low": seconds(min(row["seconds"])),
            "high": seconds(max(row["seconds"])),
            "recorded": recorded(row["recorded"], sections),
        }
        for row in builds["rows"]
    ]
    coverage = data["coverage"]
    return {
        "runs": runs,
        "landing": landing,
        "builds": {**builds, "rows": rows},
        "coverage": {**coverage, "statements": f"{coverage['statements']:,}", "covered": f"{coverage['covered']:,}"},
        "page_url": PAGE_URL,
    }


def page(data: dict[str, Any]) -> str:
    """The measured-numbers page, rendered from the data alone."""
    template = jinja2.Template(
        TEMPLATE.read_text(encoding="utf-8"), keep_trailing_newline=True, undefined=jinja2.StrictUndefined
    )
    return template.render(view(data))


def readme_block(data: dict[str, Any]) -> str:
    """The README's measured lines: the first landing row, the three builds and the coverage, with the link."""
    shown = view(data)
    row = shown["landing"][0]
    builds = shown["builds"]
    cold, unchanged, changed = builds["rows"]
    run = shown["runs"][row["run"]]
    over = row["over_limit"]
    limit = f"{row['limit']} plus half a frame"
    landed = (
        f"Every reveal of the starter landed within {row['worst']} of its word, against a limit of {limit}, "
        f"with a median of {row['median']} over {row['reveals']} reveals in {run['repeats']} builds."
        if not over
        else f"The starter's reveals landed a median of {row['median']} from their word over {row['reveals']} "
        f"reveals in {run['repeats']} builds. The worst was {row['worst']} against a limit of {limit}, "
        f"and {over} of {row['reveals']} reveals landed past {row['limit']} alone."
    )
    lines = [
        f"- **Landing.** {landed}",
        f"- **Builds.** A cold build of its {builds['film_seconds']} second film took {cold['median']}, the "
        f"same build with nothing changed {unchanged['median']}, and the build after one changed word "
        f"{changed['median']}, recording {changed['recorded']} sections again.",
        f"- **Coverage.** The suites reach {shown['coverage']['percent']} percent of the package's statements.",
        "",
        f"Measured on {run['machine']['platform']} ({run['machine']['cpu']}) with DeckTalk "
        f"{run['versions']['decktalk']} and placeholder takes. "
        f"[Every number and how it was measured]({PAGE_URL}).",
    ]
    return "\n" + "\n".join(lines) + "\n"


def documents() -> dict[Path, str]:
    """The page and the README with its block filled, both from the committed data file."""
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    readme = generated.splice(README.read_text(encoding="utf-8"), MARKERS, readme_block(data), where=README)
    return {PAGE: page(data), README: readme}


if __name__ == "__main__":
    sys.exit(generated.run(documents))
