# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/reference/cli.mdx from the parser in src/decktalk/cli/parser.py.

    uv run scripts/build_cli_reference.py            # write the page
    uv run scripts/build_cli_reference.py --check    # exit 1 if the committed page would change

Every command, its purpose line, its usage line and each of its options come from the parser
itself, so the reference cannot drift from the command line. A command that gains a flag, or loses
one, changes this page by being run. Edit the parser, then run this.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from decktalk.cli.envelope import SCHEMA  # noqa: E402  (after sys.path, so a checkout needs no install)
from decktalk.cli.parser import COMMANDS, Command, build_parser, command_parsers  # noqa: E402

TARGET = ROOT / "docs" / "reference" / "cli.mdx"

# The flags every command shares. They are listed once, and a command's own table leaves them out.
SHARED = ("help", "verbose", "quiet", "json", "project", "strict", "exit_zero")

HEADER = rf"""---
title: CLI
description: Look up every decktalk command, its options, its output and its exit codes.
---

{{/* Generated by scripts/build_cli_reference.py from src/decktalk/cli/parser.py. Do not edit by hand. */}}

The `decktalk` command runs each stage on its own, or the whole pipeline with `decktalk build`.
This page lists every command with its options, and it is generated from the parser, so a flag on
this page is a flag the command takes.

## Global options

These work with every command, before or after the command name.

| Option | Meaning |
|---|---|
| `-p PROJECT`, `--project PROJECT` | The project directory. Defaults to `DECKTALK_PROJECT`, then the current directory. `init`, `install` and `doctor` ignore it. |
| `-v`, `--verbose` | Debug logging on stderr, including every ffmpeg command line and the traceback of a bug. |
| `-q`, `--quiet` | Warnings and errors only on stderr. |
| `--json` | Print one JSON envelope on stdout and nothing else there. Every log line goes to stderr. |
| `--strict` | An uncertain finding fails as a certain one does. Only on a command that can report one. |
| `--exit-zero` | Exit 0 whatever was found, for a caller that reads the envelope itself. It never hides an error. |
| `--version` | Print the version and exit 0. |
| `-h`, `--help` | Print the usage and exit 0. |

A `--only` value is a section number, a list or a range: `--only 3`, `--only 3,5`, `--only 7-9`.
The flag repeats, and the values gather into one list.

## Environment variables

| Variable | Default | Meaning |
|---|---|---|
| `DECKTALK_PROJECT` | none | Default project directory. |
| `DECKTALK_CONFIG` | per platform, below | Per-machine settings file. |
| `DECKTALK_CACHE_DIR` | per platform, below | ffmpeg cache. Playwright keeps Chromium in its own cache. |
| `DECKTALK_FFMPEG`, `DECKTALK_FFPROBE` | none | Paths to your own binaries. Set both. They win over the pinned build and `PATH`. |
| `DECKTALK_<TABLE>_<FIELD>` | none | One tuning field, such as `DECKTALK_VIDEO_PRESET=veryfast`. |
| `DECKTALK_ALLOW_ANY_API_BASE` | unset | Lets `[elevenlabs] api_base` name any host, for a local mock of the API. It is a switch and never a secret, and without it the key goes only to an https ElevenLabs host. |
| `ELEVENLABS_API_KEY`, `ELEVENLABS_VOICE_ID` | none | Speech provider secrets. Also read from `.env`. |

| Default path | Linux | macOS | Windows |
|---|---|---|---|
| `DECKTALK_CONFIG` | `$XDG_CONFIG_HOME/decktalk/decktalk.toml`, else `~/.config/decktalk/decktalk.toml` | `~/Library/Application Support/decktalk/decktalk.toml` | `%APPDATA%\decktalk\decktalk.toml` |
| `DECKTALK_CACHE_DIR` | `$XDG_CACHE_HOME/decktalk`, else `~/.cache/decktalk` | `~/Library/Caches/decktalk` | `%LOCALAPPDATA%\decktalk` |

Note: a key value that starts with `<` counts as unset, so the placeholders in `.env.example` never
reach the provider. No value of any variable on this page is printed, logged or put in a payload. [Configuration](/reference/configuration) lists every tuning field.

## Exit codes

| Code | Meaning | How a caller tells |
|---|---|---|
| 0 | The command ran and found nothing, or `--exit-zero` was passed. | `ok` is true, or `exit_code` is 0 with findings present. |
| 1 | The command ran and found something. | `error` is null and a findings count is above zero. |
| 2 | A usage error: an unknown command, an unknown flag or a bad value. | `error.code` is `USAGE`. |
| 3 | DeckTalk itself could not run. Stop and tell the user. | `error` is not null and names the error class. |
| 130 | The run was interrupted. No envelope is promised. | The process was signalled. |

A non-zero exit with `error: null` is a finding, and the project is what to fix. A non-null
`error.code` is an error, and the run stops.

## The `--json` envelope

Every command prints exactly one object on stdout under `--json`, and an error prints it too.

| Field | Type | Meaning |
|---|---|---|
| `schema` | integer | The envelope's shape version, {SCHEMA} today. It moves only when the shape changes. |
| `version` | string | The installed DeckTalk version. |
| `command` | string | The command as typed. |
| `ok` | boolean | True when the command found nothing and raised nothing. It ignores `--exit-zero`. |
| `exit_code` | integer | The code the process is about to return. |
| `summary` | object | The counts that lead the output. The keys are the command's own. |
| `findings` | object | `certain`, `uncertain` and `items`, the rows. |
| `written` | array | Every file the command wrote, project-relative, in the order written. |
| `error` | object or null | `code`, `message`, `hint`, `path` and `line`. Null on success and on a finding. |
| `<command>` | object | The command's own payload, under the first word of its name. |

`findings.items[]` has one shape on every command, and the certain rows lead it.

| Key | Type | Meaning |
|---|---|---|
| `code` | string | The verdict code, such as `OFF_CUE`. Match on this. `MISSING` is a file that is not there and `UNREADABLE` is a file that is there and does not parse. |
| `label` | string | The printed label, such as `OFF CUE`. Nothing parses it. |
| `certain` | boolean | True when the finding is certain. |
| `section` | integer or null | The section number. |
| `cue` | string or null | The cue id. |
| `where` | string or null | The file, page or artifact the row is about. |
| `detail` | string or null | One sentence, with any measured number in it. |

## The progress log

`decktalk build` truncates and then appends JSON Lines to `build/progress.jsonl`, relocatable with
`--progress PATH`, so a caller polls a file instead of tailing a log.

| Key | Type | Meaning |
|---|---|---|
| `ts` | string | The event time, as an ISO 8601 timestamp. |
| `pid` | integer | The process running the build, which is how `status` answers `alive`. |
| `stage` | string | A stage this run executes, named as `build` runs it. |
| `stage_index` | integer | The stage's place in this run, counting from 1. |
| `stage_count` | integer | How many stages this run will execute. |
| `section` | integer or null | The section the event is about. |
| `event` | string | `start`, `done`, `skip` or `fail`. |
| `detail` | string or null | One sentence of detail. |

`decktalk status --json` reads `build/progress.jsonl` and reports `run`, so a caller polls one
command instead of tailing a log. It is null when no build has written a log there, which is also
what a build started with `--progress PATH` leaves behind.

| Key | Type | Meaning |
|---|---|---|
| `pid` | integer or null | The process that wrote the log. |
| `started` | string or null | When the run began. |
| `stage` | string or null | The stage the last event named. |
| `sections_done` | integer or null | Sections finished, and null until a stage reports per section. |
| `sections_total` | integer or null | Sections the run will do, and null for the same reason. |
| `alive` | boolean | True while the run is unfinished and its process is still on this machine. |
"""

FOOTER = """
## See also

- [Configuration](/reference/configuration) lists every tuning field.
- [Python API](/reference/python-api) lists everything `decktalk.__all__` holds.
"""


def cell(text: object) -> str:
    """One table cell, with the pipe that would break a row escaped."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def default_of(action: argparse.Action) -> str:
    """How a flag's default reads in the table, and nothing at all when it has none."""
    value = action.default
    if value is argparse.SUPPRESS or value is None:
        return ""
    if isinstance(value, bool):
        return "off" if value is False else "on"
    return f"`{value}`"


def options_of(parser: argparse.ArgumentParser) -> list[argparse.Action]:
    """A command's own arguments, in the order it declares them, without the shared flags."""
    # argparse exposes no public reader for the arguments a parser holds.
    return [a for a in parser._actions if a.dest not in SHARED]  # noqa: SLF001


def shared_of(command: Command) -> str:
    """The sentence naming which shared flags this command takes."""
    flags = ["`--json`", "`-v`", "`-q`"]
    if command.project:
        flags.insert(0, "`-p`")
    if command.strict:
        flags.append("`--strict`")
    if command.exit_zero:
        flags.append("`--exit-zero`")
    return f"It also takes {', '.join(flags[:-1])} and {flags[-1]}."


def section(command: Command, parser: argparse.ArgumentParser) -> list[str]:
    """One command: its purpose, the line it is written on, and the options of its own."""
    usage = " ".join(parser.format_usage().replace("usage: ", "").split())
    lines = [f"### `decktalk {command.name}`\n", f"{command.purpose[0].upper()}{command.purpose[1:]}.\n"]
    lines += ["```text", usage, "```\n"]
    own = options_of(parser)
    if own:
        lines.append("| Option | Default | Meaning |")
        lines.append("|---|---|---|")
        for action in own:
            names = ", ".join(f"`{s}`" for s in action.option_strings) or f"`{action.dest.upper()}`"
            lines.append(f"| {names} | {default_of(action)} | {cell(action.help or '')} |")
        lines.append("")
    lines.append(f"{shared_of(command)}\n")
    return lines


def render() -> str:
    parsers = command_parsers()
    parts = [HEADER]
    for group in dict.fromkeys(c.group for c in COMMANDS):
        parts.append(f"## {group[0].upper()}{group[1:]}\n")
        for command in COMMANDS:
            if command.group == group:
                parts += section(command, parsers[command.name])
    parts.append(FOOTER.strip())
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    build_parser()  # the page is worthless if the parser cannot be built at all
    text = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"stale: {TARGET.relative_to(ROOT)}")
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
