# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/reference/what-leaves-your-machine.mdx from docs/data/outbound.toml.

    uv run scripts/build_outbound_reference.py --write    # write the page
    uv run scripts/build_outbound_reference.py --check    # exit 1 if the committed page would change

Every host on the page comes from the data file, so the page is a complete list by construction.
Add a host to docs/data/outbound.toml, then run this.
"""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "data" / "outbound.toml"
TARGET = ROOT / "docs" / "reference" / "what-leaves-your-machine.mdx"

HEADER = """---
title: What leaves your machine
description: Every host DeckTalk contacts, what each request carries, and how to build with no network at all.
---

{/* Generated by scripts/build_outbound_reference.py from docs/data/outbound.toml. Do not edit by hand. */}

This page is the whole list. DeckTalk contacts the hosts below and no others, and it sends no
telemetry, no usage report and no crash report anywhere. A host that is not named on this page is a
host DeckTalk does not contact.

Hand this page to a reviewer who has to approve DeckTalk on a managed machine. The two facts that
decide most reviews are that a cloud speech service receives your script, and that the first run
downloads a browser and a media tool.

## Requests that carry your content

These requests carry text from your project. Every one of them is made only by a command you run on
purpose, and every one of them needs an API key that you supply.
"""

SERVICE_TAIL = """
### Reading a request before you make it

`decktalk check --json` prices a voiced run with no API key and no request. Its `spend` object
reports the sections a voiced run would pay for, their character count, the price per thousand
characters and the layer that set it, so a reviewer can read exactly what would be sent before
anything is sent. `decktalk build` stops at the same point and names the price before it spends a
credit, and `--max-cost N` refuses the whole run before the first call when the ceiling is above N.

Set `narration.context_chars = 0` when the neighbouring sections must stay on the machine. Each
section is then sent on its own, with no surrounding text.
"""

DOWNLOAD_HEAD = """
## One-time downloads

DeckTalk fetches the tools a recording needs, once per machine: the first command that opens a page
downloads the browser, the first command that encodes downloads the media tool, and `decktalk
install` does both up front. These requests carry nothing from your project, and after they succeed
a build without voice needs no network at all.
"""

TAIL = """
## What never leaves

DeckTalk has no telemetry. It reports no usage, no errors and no project contents to its authors,
and it has no update check. Nothing about a build is sent anywhere unless a command in the first
table above sends it.

No DeckTalk environment variable has its value printed, logged or placed in a request body. The one
exception is `DECKTALK_ALLOW_ANY_API_BASE`, which is a switch and never a secret. An error message
that quotes a reply from a service has every credential in it replaced before the quote is cut to
length.

KaTeX ships inside the wheel, so an equation needs no download and no content delivery network.

## The agent is a second service

The six DeckTalk skills run inside your coding agent. When you ask an agent to write a script,
place cues or fix a finding, the agent puts your `script.md`, your `decktalk.toml`, your `cues.json`
and the JSON that DeckTalk prints in front of whatever model that agent runs. That model is a cloud
service of its own, under its vendor's terms and not under DeckTalk's, and a policy review that
covers the speech service should cover it too. Running DeckTalk from the command line alone contacts
no model.

## On a managed machine

A laptop with an intercepting proxy, no administrator rights and a policy review needs four things,
and none of them is a DeckTalk feature you have to wait for.

- **Build with no voice and no key.** `decktalk build --no-voice` writes placeholder narration and
  makes a complete video. It contacts no service, so you can show a finished internal video before
  any approval comes back.
- **Use the browser the machine already has.** Set `[record] browser_path` in `decktalk.toml`, or
  point `PLAYWRIGHT_BROWSERS_PATH` at a location your administrators have already filled. The
  pinned build is the reference, and a managed browser is supported and unverified.
- **Use the ffmpeg the machine already has.** `[tools] ffmpeg` and `[tools] ffprobe` name
  executables directly, and a build that finds them downloads nothing from the second table. Both
  are machine keys, so they belong in this machine's settings file rather than in a project that
  ships to somebody else.
- **Ask the proxy to leave the local origin alone.** Pages record over a virtual origin on the
  loopback address, so the proxy rules need a bypass for it. `decktalk serve` binds to the loopback
  address and takes `--host` and `--port`.

[Requirements and costs](/requirements) has the full managed-machine section, with the package index
mirror, `PLAYWRIGHT_BROWSERS_PATH` and the `[tools]` keys.

`decktalk doctor` reports what is installed and which browser and media build a run would use,
without fetching anything, and `decktalk doctor --json` prints the same reading as one object with
no credential in it.
"""


def rows(items: list[dict[str, Any]], keys: tuple[str, ...]) -> list[str]:
    return ["| " + " | ".join(str(item[k]) for k in keys) + " |" for item in items]


def render(data: dict[str, Any]) -> str:
    services = data.get("service", [])
    downloads = data.get("download", [])
    out = [HEADER.strip(), ""]
    out.append("| Host | Request | Sent by | What DeckTalk sends |")
    out.append("|---|---|---|---|")
    out.extend(rows(services, ("host", "name", "sent_by", "body")))
    out.append("")
    for item in services:
        out.append(f"**{item['name']} to `{item['host']}`.** {item['credential']} {item['note']}")
        out.append("")
    out.append(SERVICE_TAIL.strip())
    out.append("")
    out.append(DOWNLOAD_HEAD.strip())
    out.append("")
    out.append("| Host | What it holds | Fetched by | What DeckTalk sends |")
    out.append("|---|---|---|---|")
    out.extend(rows(downloads, ("host", "name", "sent_by", "body")))
    out.append("")
    for item in downloads:
        out.append(f"**`{item['host']}`.** {item['note']}")
        out.append("")
    out.append(TAIL.strip())
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    action = ap.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="write the page")
    action.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    page = render(tomllib.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != page:
            print(f"{TARGET.relative_to(ROOT)} is out of date. Run: uv run scripts/build_outbound_reference.py --write")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date.")
        return 0
    TARGET.write_text(page, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
