"""Generate the skills table in docs/agents/skills.mdx from the packaged SKILL.md front matter.

    uv run scripts/build_skills_list.py --write    # write the table
    uv run scripts/build_skills_list.py --check    # exit 1 if the committed page would change

Each row is one packaged skill: its name, when it starts and what it leaves behind. The first two
come from the skill's own `description`, whose second sentence is the trigger the skill was written
to be chosen by, so the page and the skill cannot say different things about when to reach for it.
The last column is the skill's `metadata.ends_with`, which is the one line the page needs and a
reader of the skill does not.

Everything outside the table is prose in the page itself.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import generated  # noqa: E402
from decktalk.template import SKILL_NAMES  # noqa: E402  (after sys.path)
from decktalk.toolchain import assets  # noqa: E402

TARGET = ROOT / "docs" / "agents" / "skills.mdx"

MARKERS = ("{/* skills:start */}", "{/* skills:end */}")


def front_matter(text: str) -> dict[str, str]:
    """The skill's front matter, with one level of nesting flattened and a folded value joined.

    `metadata.ends_with` arrives as `ends_with`, because the front matter's keys are fixed and a
    page-only line lives under `metadata` rather than beside `name` and `description`.
    """
    head = text[4:].partition("\n---\n")[0]
    doc: dict[str, str] = {}
    key = ""
    for line in head.splitlines():
        nested = re.match(r"^(\s+)([a-zA-Z][\w-]*):\s*(.*)$", line)
        if re.match(r"^[a-zA-Z][\w-]*:", line):
            key, _, value = line.partition(":")
            key = key.strip()
            doc[key] = value.strip()
        elif nested:
            key = nested.group(2)
            doc[key] = nested.group(3).strip()
        elif key and line.strip():
            doc[key] = f"{doc[key]} {line.strip()}".strip()
    return doc


def trigger(description: str) -> str:
    """The sentence of a description that says when to use the skill, as the table's middle column."""
    for sentence in re.split(r"(?<=\.)\s+", description):
        if sentence.startswith("Use when "):
            return sentence[len("Use when ") :].strip()
    return description.split(". ")[0].strip() + "."


def rows() -> list[str]:
    """One row per packaged skill, in the order an author meets them, which the package declares."""
    out: list[str] = []
    for name in SKILL_NAMES:
        doc = front_matter((assets.package_file("skills") / name / "SKILL.md").read_text(encoding="utf-8"))
        out.append(f"| `{doc['name']}` | {trigger(doc['description'])} | {doc['ends_with'].rstrip()} |")
    return out


def documents() -> dict[Path, str]:
    """The skills page with its table written from the packaged skills, and every other line kept."""
    table = "\n".join(["| Skill | It starts when | It ends with |", "|---|---|---|", *rows()])
    block = f"\n{{/* Generated by scripts/build_skills_list.py. Do not edit by hand. */}}\n\n{table}\n"
    return {TARGET: generated.splice(TARGET.read_text(encoding="utf-8"), MARKERS, block, where=TARGET)}


if __name__ == "__main__":
    sys.exit(generated.run(documents))
