# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/reference/configuration.mdx from the tuning dataclasses in src/decktalk/settings.py.

    uv run scripts/build_settings_reference.py            # write the page
    uv run scripts/build_settings_reference.py --check    # exit 1 if the committed page would change

Every field, its type, its default, the range it accepts and its sentence come from the dataclass
field itself, so the reference cannot drift from the code. Edit settings.py, then run this.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import MISSING, dataclass, fields
from pathlib import Path
from typing import Any, get_type_hints

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from decktalk.settings import Settings  # noqa: E402  (after sys.path, so a checkout needs no install)

TARGET = ROOT / "docs" / "reference" / "configuration.mdx"

HEADER = """---
title: Configuration
description: Look up every DeckTalk tuning field, with its type, its default, and what it changes.
---

{/* Generated by scripts/build_settings_reference.py from src/decktalk/settings.py. Do not edit by hand. */}

Tuning fields change how DeckTalk records, assembles, and checks a video. This page lists every
field, grouped by table, with its type, its default, and the values it accepts. A field whose Value
column is empty takes any value of its type, and a value outside the stated range fails the load
with the table and the field named.

A tuning table can go in the project's `decktalk.toml`. The same field can also come from an
environment variable.

```toml decktalk.toml
[video]
preset = "veryfast"
```

```console
DECKTALK_VIDEO_PRESET=veryfast decktalk build --no-voice
```

The scaffold builds with every default. Change `[video]` for faster drafts. Change `[verify]` when a
small reveal fails the cue check.

## Which value wins

Five layers can set a field. Each layer overrides the layers before it.

1. The default on this page.
2. The same table in the per-machine settings file.
3. The same table in the project's `decktalk.toml`.
4. An environment variable named `DECKTALK_<TABLE>_<FIELD>`, such as `DECKTALK_VIDEO_PRESET`.
5. A command-line flag, for one run.

The per-machine settings file is in a different place on each platform.

| Linux | macOS | Windows |
|---|---|---|
| `$XDG_CONFIG_HOME/decktalk/decktalk.toml`, or `~/.config/decktalk/decktalk.toml` when `XDG_CONFIG_HOME` is not set | `~/Library/Application Support/decktalk/decktalk.toml` | `%APPDATA%\\decktalk\\decktalk.toml` |

Note: `DECKTALK_CONFIG` points at a different file. The per-machine file can hold only the tables on
this page, and any other table fails the load. `decktalk doctor` prints the path in its `config` row.

An environment variable for an array field takes comma-separated values, such as
`DECKTALK_VERIFY_PROBE_DELAYS=0.7,1.5`.

Four flags override a field for one run.

| Flag | Commands | Overrides |
|---|---|---|
| `--preset` | `assemble`, `build` | `[video] preset` |
| `--crf` | `assemble`, `build` | `[video] crf` |
| `--settle` | `record` | `[record] settle_seconds` |
| `--model` | `narrate` | `[narration] model` and `[voice] model` |

Sections, the voice, mix levels, and soundscape prompts are project content, not tuning.
[decktalk.toml](/reference/decktalk-toml) lists those tables. Secrets go only in `.env`.
"""

FOOTER = """## Related

- **Set sections, the voice, and the mix:** [decktalk.toml](/reference/decktalk-toml)
- **Understand the `[verify]` fields:** [Verify](/reference/verify)
- **Override a field for one run:** [CLI](/reference/cli)
"""

# The words the docs use for types (style rule S22), keyed by the field's own annotation.
TYPE_WORDS = {
    "int": "integer",
    "float": "number",
    "str": "string",
    "bool": "boolean",
    "tuple[float, ...]": "array of numbers",
}


@dataclass
class Field:
    name: str
    type: str
    default: str
    rule: str
    doc: str


@dataclass
class Section:
    key: str
    doc: str
    fields: list[Field]


def type_word(annotation: Any) -> str:
    """The word the docs use for a field's type."""
    name = str(annotation) if hasattr(annotation, "__origin__") else getattr(annotation, "__name__", str(annotation))
    return TYPE_WORDS.get(name, name)


def toml_value(value: Any) -> str:
    """The default as it would be written in decktalk.toml."""
    if value is MISSING:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, (tuple, list)):
        return "[" + ", ".join(toml_value(x) for x in value) + "]"
    return repr(value)


def tables() -> list[Section]:
    """One section per tuning table, read from the fields of Settings and of each table's dataclass."""
    out: list[Section] = []
    for table in fields(Settings):
        cls = get_type_hints(Settings)[table.name]
        hints = get_type_hints(cls)
        rows = [
            Field(
                f.name,
                type_word(hints[f.name]),
                toml_value(f.default),
                getattr(f.metadata.get("check"), "must", "") or "",
                str(f.metadata.get("doc", "")),
            )
            for f in fields(cls)
        ]
        out.append(Section(table.name, (cls.__doc__ or "").strip(), rows))
    return out


def render(sections: list[Section]) -> str:
    parts = [HEADER]
    for s in sections:
        parts.append(f"## `[{s.key}]`\n")
        if s.doc:
            parts.append(f"{s.doc} Environment variables start with `DECKTALK_{s.key.upper()}_`.\n")
        else:
            parts.append(f"Environment variables start with `DECKTALK_{s.key.upper()}_`.\n")
        parts.append("| Field | Type | Default | Value | Meaning |\n|---|---|---|---|---|")
        for f in s.fields:
            default = f"`{f.default}`" if f.default else ""
            parts.append(f"| `{f.name}` | `{f.type}` | {default} | {f.rule} | {f.doc} |")
        parts.append("")
    parts.append(FOOTER)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    text = render(tables())
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"stale: {TARGET.relative_to(ROOT)}")
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
