# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/changelog.mdx from CHANGELOG.md, which release-please writes.

    uv run scripts/build_changelog.py            # write the page
    uv run scripts/build_changelog.py --check    # exit 1 if the committed page would change

Each release heading becomes a Mintlify Update component, so the docs site shows the
changelog with a table of contents per release and serves an RSS feed at /changelog/rss.xml.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "CHANGELOG.md"
TARGET = ROOT / "docs" / "changelog.mdx"

HEADER = """---
title: Changelog
description: See what changed in each DeckTalk release, including the file formats and the page contract.
mode: "center"
---

{/* Generated by scripts/build_changelog.py from CHANGELOG.md. Do not edit by hand. */}

This page lists every DeckTalk release, newest first. DeckTalk follows semantic versioning.

A change to a file format or to the page contract raises the minor version. It comes with a
migration note. The file formats are `decktalk.toml`, `cues.json`, and the build artifacts.

After an upgrade, run `decktalk runtime` to update `deck/decktalk-runtime.js`.
"""

RELEASE_RE = re.compile(r"^## \[?(?P<version>\d+\.\d+\.\d+)\]?(?:\([^)]*\))? \((?P<date>\d{4}-\d{2}-\d{2})\)\s*$")
SECTION_RE = re.compile(r"^### (?P<name>.+?)\s*$")
TAGS = {"Features": "feature", "Bug Fixes": "fix", "Documentation": "docs", "Performance Improvements": "performance"}


def parse(text: str) -> list[dict]:
    releases: list[dict] = []
    current: dict | None = None
    for line in text.splitlines():
        m = RELEASE_RE.match(line)
        if m:
            current = {"version": m["version"], "date": m["date"], "lines": [], "tags": []}
            releases.append(current)
            continue
        if current is None:
            continue
        s = SECTION_RE.match(line)
        if s:
            tag = TAGS.get(s["name"])
            if tag and tag not in current["tags"]:
                current["tags"].append(tag)
            current["lines"].append(f"**{s['name']}**")
            continue
        current["lines"].append(line)
    return releases


def render(releases: list[dict]) -> str:
    parts = [HEADER]
    for r in releases:
        body = "\n".join(r["lines"]).strip("\n")
        body = re.sub(r"\n{3,}", "\n\n", body)
        tags = ", ".join(f'"{t}"' for t in r["tags"]) or '"release"'
        parts.append(
            f'<Update label="{r["version"]}" description="{r["date"]}" tags={{[{tags}]}}>\n\n{body}\n\n</Update>\n'
        )
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    text = render(parse(SOURCE.read_text()))
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print(f"stale: {TARGET.relative_to(ROOT)}")
            return 1
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
