# /// script
# requires-python = ">=3.12"
# ///
"""Generate the module tree and the check table in CONTRIBUTING.md from the code itself.

    uv run scripts/build_contributing.py --write    # write both blocks
    uv run scripts/build_contributing.py --check    # exit 1 if either block would change

The module tree is one line per module of `src/decktalk`, and its sentence is the first sentence of
that module's own docstring, so a module that is added, renamed or repurposed changes this tree by
being written. The order is the import order, read from the `LAYERS` table in
`tests/contract/test_imports.py`, which is the table the suite enforces, so the tree a newcomer
reads and the layering a pull request must obey are the same table.

The check table is one line per row of `GROUPS` in `scripts/check.py`, which is the only place any
check is written down. It lists what each group runs, what it needs, where it runs and when it
gates, so a contributor never opens a workflow file and a hand-written wall time can never drift
from the measured one.

A directory of the package that holds no Python needs a line here, because a `.js` file has no
docstring to read. The script fails on a data directory it has never heard of, so one cannot be
added without a sentence about it.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "decktalk"
IMPORT_TEST = ROOT / "tests" / "contract" / "test_imports.py"
CHECK_SCRIPT = ROOT / "scripts" / "check.py"
TARGET = ROOT / "CONTRIBUTING.md"

STALE = "stale: {path}. Run `uv run scripts/{script} --write` to bring it up to date."
"""The one sentence every generator fails with, naming the file and the command that fixes it."""

LAYOUT = ("<!-- layout:start -->", "<!-- layout:end -->")
CHECKS = ("<!-- checks:start -->", "<!-- checks:end -->")

NOTE = "<!-- Generated by scripts/build_contributing.py. Do not edit by hand. -->"

LAYER_NOTES = {
    "vocabulary": "the names every layer above shares, which import nothing but each other",
    "models": "the frozen models and the settings tree, which every layer above reads",
    "leaves": "one job each, and no knowledge of a project",
    "sdk": "the object a caller drives, and the stages it drives",
    "cli": "the first client, and the package's public surface",
}
"""What each layer holds, in one clause, for the line that opens it. The names are the LAYERS table's."""

DATA_DIRS = {
    "runtime": "decktalk-runtime.js, the page contract every deck loads, decktalk-probe.js and contract.json",
    "katex": "The pinned KaTeX release the pages typeset with, copied into a project by `decktalk init`",
    "template": "The starter, the lesson example and the AGENTS.md that `decktalk init` writes",
    "skills": "The six packaged skills a project keeps in .agents/skills/",
}
"""The directories of the package that hold no Python. A new one fails the run until it is named here."""


def layers() -> dict[str, tuple[str, int]]:
    """The layer and rank of every top-level module, read from the table the test suite enforces."""
    tree = ast.parse(IMPORT_TEST.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "LAYERS" and node.value:
            return ast.literal_eval(node.value)
    raise SystemExit(f"{IMPORT_TEST.relative_to(ROOT)} has no LAYERS table to read the import order from.")


def groups() -> tuple[object, ...]:
    """The frozen `GROUPS` table, imported from the one file that spells a check."""
    spec = importlib.util.spec_from_file_location("decktalk_check_table", CHECK_SCRIPT)
    if spec is None or spec.loader is None:
        raise SystemExit(f"{CHECK_SCRIPT.relative_to(ROOT)} could not be read, so no check table exists.")
    module = importlib.util.module_from_spec(spec)
    # A frozen dataclass looks its own module up while it is being built, so it has to be registered.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return tuple(module.GROUPS)


def summary(path: Path) -> str:
    """The first sentence of a module's docstring, which is the one line the tree has room for."""
    doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    first = doc.strip().split("\n\n")[0].replace("\n", " ").strip()
    if not first:
        raise SystemExit(f"{path.relative_to(ROOT)} has no docstring, so the module tree has no line for it.")
    return re.split(r"(?<=[.!?])\s", first)[0].strip()


def entries(directory: Path, depth: int) -> list[tuple[int, str, str]]:
    """One row per module and package under `directory`, deepest last, each as (depth, name, line)."""
    rows: list[tuple[int, str, str]] = []
    for path in sorted(directory.iterdir(), key=lambda p: (p.is_dir(), p.name)):
        if path.is_dir() and (path / "__init__.py").is_file():
            rows.append((depth, f"{path.name}/", summary(path / "__init__.py")))
            rows += entries(path, depth + 1)
        elif path.suffix == ".py" and path.name != "__init__.py":
            rows.append((depth, path.name, summary(path)))
    return rows


def package_rows() -> list[tuple[int, str, str]]:
    """Every row of the tree: the layers in import order, then the directories that hold no Python."""
    rows: list[tuple[int, str, str]] = []
    ranked = sorted(layers().items(), key=lambda item: (item[1][1], item[0]))
    for layer in dict.fromkeys(rank[0] for _, rank in ranked):
        if layer not in LAYER_NOTES:
            raise SystemExit(f"the {layer} layer has no clause in LAYER_NOTES, so its line cannot be written.")
        rows.append((0, layer, LAYER_NOTES[layer]))
        for name, _ in [item for item in ranked if item[1][0] == layer]:
            module, package = SRC / f"{name}.py", SRC / name
            if package.is_dir() and (package / "__init__.py").is_file():
                rows.append((1, f"{name}/", summary(package / "__init__.py")))
                rows += entries(package, 2)
            elif module.is_file():
                rows.append((1, f"{name}.py", summary(module)))
            else:
                raise SystemExit(f"{name} is ranked in LAYERS and is neither a module nor a package.")

    rows.append((0, "packaged data", "what ships in the wheel and holds no Python"))
    known = {p.name for p in SRC.iterdir() if p.is_dir() and not (p / "__init__.py").is_file()}
    known -= {"__pycache__"}  # a build leaves it behind, and no clone holds it
    if unknown := known - set(DATA_DIRS):
        raise SystemExit(f"{', '.join(sorted(unknown))} under {SRC.name}/ needs a line in DATA_DIRS.")
    rows += [(1, f"{name}/", DATA_DIRS[name]) for name in sorted(known)]
    return rows


def render_tree() -> str:
    """The tree as one text block, with every sentence in one column."""
    rows = package_rows()
    width = max(len(name) + 2 * depth for depth, name, _ in rows) + 2
    lines = ["```text", "src/decktalk/"]
    for depth, name, line in rows:
        indent = "  " * (depth + 1)
        lines.append(f"{indent}{name}".ljust(width + 2) + line)
    lines.append("```")
    return "\n".join(lines)


def shell(command: tuple[str, ...]) -> str:
    """One command as a person types it, with this checkout's own path and any script left out."""
    parts = ["<shell script>" if "\n" in part else part.replace(f"{ROOT}/", "") for part in command]
    return " ".join(parts)


def runner_names(runners: tuple[str, ...]) -> str:
    """The runners of one row, as the words a contributor uses rather than the labels GitHub uses."""
    words = {"ubuntu-latest": "Linux", "macos-latest": "macOS", "windows-latest": "Windows"}
    return ", ".join(words.get(name, name) for name in runners)


def render_checks() -> str:
    """The check table as a Markdown table and a command list, both read from `GROUPS`."""
    rows = groups()
    lines = [
        "| Group | What it runs | Needs | Where | Gates on |",
        "|---|---|---|---|---|",
    ]
    for group in rows:
        first = shell(group.commands[0])
        more = f", and {len(group.commands) - 1} more" if len(group.commands) > 1 else ""
        lines.append(
            f"| `{group.name}` | `{first}`{more} | {', '.join(group.tools)} | "
            f"{runner_names(group.runners)} | {', '.join(group.when)} |"
        )
    lines.append("")
    lines.append("Every group, one at a time:")
    lines.append("")
    lines.append("```console")
    # The comment column is measured from the longest row rather than typed, so a group whose name
    # grows still leaves a space between the command and the sentence that explains it.
    calls = [f"uv run scripts/check.py --group {group.name}" for group in rows]
    column = max(len(call) for call in calls) + 1
    for call, group in zip(calls, rows, strict=True):
        lines.append(call.ljust(column) + f"# {group.why}")
    lines.append("```")
    return "\n".join(lines)


def fill(page: str, markers: tuple[str, str], block: str) -> str:
    """One generated block written between its markers, with the note that says not to edit it."""
    start, end = markers
    if start not in page or end not in page:
        raise SystemExit(f"{TARGET.name} has no {start} ... {end} block to fill.")
    head, _, rest = page.partition(start)
    _, _, tail = rest.partition(end)
    return f"{head}{start}\n{NOTE}\n\n{block}\n{end}{tail}"


def render(page: str) -> str:
    return fill(fill(page, LAYOUT, render_tree()), CHECKS, render_checks())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if either generated block would change")
    parser.add_argument("--write", action="store_true", help="write both generated blocks")
    args = parser.parse_args()

    current = TARGET.read_text(encoding="utf-8")
    page = render(current)
    if not args.write:
        if current != page:
            print(STALE.format(path=TARGET.relative_to(ROOT), script="build_contributing.py"))
            return 1
        print(f"{TARGET.name} is up to date.")
        return 0
    TARGET.write_text(page, encoding="utf-8")
    print(f"wrote {TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
