# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/reference/configuration.mdx from the dataclasses in src/decktalk/config.py.

    uv run scripts/build_config_reference.py            # write the page
    uv run scripts/build_config_reference.py --check    # exit 1 if the committed page would change

Every field, its type, its default, and the comment beside it come from the source, so the
reference cannot drift from the code. Edit config.py, then run this.
"""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "decktalk" / "config.py"
TARGET = ROOT / "docs" / "reference" / "configuration.mdx"

HEADER = """---
title: Configuration
description: Every DeckTalk tuning field with its type, its default, and the three places you can set it.
icon: "sliders"
mode: "wide"
---

{/* Generated by scripts/build_config_reference.py from src/decktalk/config.py. Do not edit by hand. */}

Tuning is everything about *how* DeckTalk renders that does not change from one
presentation to the next. It comes from four layers, and each layer overrides the one
before it.

1. The defaults on this page.
2. The same tables in a per-machine file, which is `~/Library/Application Support/decktalk/decktalk.toml` on macOS, `%APPDATA%\\decktalk\\decktalk.toml` on Windows, and `~/.config/decktalk/decktalk.toml` elsewhere. `DECKTALK_CONFIG` points at a different file. Only settings tables belong there, and `decktalk doctor` shows whether one is in use.
3. A table of the same name in the project's `decktalk.toml`. For example, `[video]` with `preset = "veryfast"` changes the x264 preset for that project.
4. An environment variable named `DECKTALK_<SECTION>_<FIELD>`. For example, `DECKTALK_VIDEO_PRESET=veryfast` changes it for one shell. A list field such as `probe_delays` takes comma-separated values.

A few command-line flags override all three for a single run: `--preset`, `--crf`,
`--settle`, and `--model`.

Content that changes per presentation is the project document, not tuning. Sections, the
voice, mix levels, and soundscape prompts live in the same file under their own tables,
and [the project file](/reference/decktalk-toml) describes them. Secrets live only in `.env`.

<Tip>You rarely need this page. The scaffold builds with every default. Reach for `[video]`
when drafts feel slow, and for `[verify]` when a deliberately subtle reveal fails the cue
check.</Tip>
"""


@dataclass
class Field:
    name: str
    type: str
    default: str
    comment: str


@dataclass
class Section:
    key: str
    cls: str
    doc: str
    fields: list[Field]


def parse(source: Path) -> list[Section]:
    tree = ast.parse(source.read_text())
    lines = source.read_text().splitlines()
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    settings = classes["Settings"]
    out: list[Section] = []
    for node in settings.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        cls = classes[ast.unparse(node.annotation)]
        fields: list[Field] = []
        for item in cls.body:
            if not isinstance(item, ast.AnnAssign) or not isinstance(item.target, ast.Name):
                continue
            line = lines[item.lineno - 1]
            comment = line.split("#", 1)[1].strip() if "#" in line else ""
            default = ast.unparse(item.value) if item.value is not None else ""
            fields.append(Field(item.target.id, ast.unparse(item.annotation), default, comment))
        out.append(Section(node.target.id, cls.name, ast.get_docstring(cls) or "", fields))
    return out


def render(sections: list[Section]) -> str:
    parts = [HEADER]
    for s in sections:
        parts.append(f"## `[{s.key}]`\n")
        if s.doc:
            parts.append(f"{s.doc} Environment variables start with `DECKTALK_{s.key.upper()}_`.\n")
        else:
            parts.append(f"Environment variables start with `DECKTALK_{s.key.upper()}_`.\n")
        parts.append("| Field | Type | Default | Notes |\n|---|---|---|---|")
        for f in s.fields:
            default = f"`{f.default}`" if f.default else ""
            parts.append(f"| `{f.name}` | `{f.type}` | {default} | {f.comment} |")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    text = render(parse(SOURCE))
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print(f"stale: {TARGET.relative_to(ROOT)}")
            return 1
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
