# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/reference/cli.mdx from the command line itself.

    uv run scripts/build_cli_reference.py --write    # write the page
    uv run scripts/build_cli_reference.py --check    # exit 1 if the committed page would change

Every command, its purpose, its usage line and each of its options come from one walk over the
parser, which is the same walk `decktalk schema` prints and the same one Click renders `--help`
from. A command that gains a flag, or loses one, changes this page by being run. Edit the command,
then run this.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from decktalk.cli import catalog  # noqa: E402  (after sys.path, so a checkout needs no install)
from decktalk.cli.options import Group  # noqa: E402

TARGET = ROOT / "docs" / "reference" / "cli.mdx"

HEADER = """---
title: CLI
description: Look up every decktalk command, its options, its output and its exit codes.
---

{/* Generated by scripts/build_cli_reference.py from src/decktalk/cli. Do not edit by hand. */}

The `decktalk` command runs one stage, the whole pipeline, or one reading of the project or the
machine. Every command prints one flat JSON object with `--json`, carrying its own fields beside
`schema`, `ok`, `findings` and `error`, and the two declared fields `run` and `written` on the
commands that open a run or write a file.
"""

GLOBALS = """
## Global options

These work with every command, before or after the command name.
"""

EXITS = """
## Exit codes
"""

ERRORS = """
## Error codes

An error means DeckTalk could not run, so nothing was judged. A finding is the other thing
entirely, which is a judgement about a film that did get made.
"""

FINDINGS = """
## Finding codes

A finding carries its code, its sentence, its certainty and often a fix an agent can apply.
`--allow CODE` carries on past one, and `--fail-on` decides which of them fails a run.
"""


def page() -> str:
    """The whole reference page, in the order a reader meets the command line."""
    parts = [HEADER, GLOBALS, _options(catalog.globals_()), EXITS, _exits(), ERRORS, _errors(), FINDINGS, _findings()]
    parts.append("\n## Commands\n")
    for group in Group:
        rows = [row for row in catalog.walk() if row["group"] == group.value]
        if not rows:
            continue
        parts.append(f"\n### {group.value}\n")
        parts.extend(_command(row) for row in rows)
    parts.append(_schema_names())
    return "".join(parts)


def _command(row: dict[str, Any]) -> str:
    """One command: what it is for, how it is written, and every option it takes."""
    name = row["command"]
    lines = [f"\n#### `decktalk {name}`\n", f"\n{row['purpose']}\n", f"\n```text\n{_usage(row)}\n```\n"]
    if row["result"]:
        lines.append(f"\nIt answers with the `{row['result']}` result: `decktalk schema {row['result']}`.\n")
    visible = [param for param in row["params"] if not param["hidden"]]
    if visible:
        lines.append(_options(visible))
    return "".join(lines)


def _usage(row: dict[str, Any]) -> str:
    """The usage line, which names the arguments a command takes and nothing it does not."""
    arguments = [param["metavar"] or param["opts"][0].upper() for param in row["params"] if _positional(param)]
    return " ".join(["decktalk", row["command"], "[OPTIONS]", *arguments])


def _positional(param: dict[str, Any]) -> bool:
    """True when this parameter is written without a flag in front of it."""
    return not any(opt.startswith("-") for opt in param["opts"])


def _options(params: list[dict[str, Any]]) -> str:
    """One table of options, in the order the command declares them."""
    rows = ["\n| Option | Meaning |", "|---|---|"]
    for param in params:
        if _positional(param):
            continue
        written = ", ".join(f"`{opt}`" for opt in param["opts"])
        metavar = f" `{param['metavar']}`" if param["metavar"] else ""
        repeats = " Repeats." if param["repeatable"] and "Repeats." not in (param["help"] or "") else ""
        rows.append(f"| {written}{metavar} | {param['help'] or ''}{repeats} |")
    return "\n".join(rows) + "\n"


def _exits() -> str:
    """The exit table, which is the two-way branch an agent writes against."""
    rows = ["\n| Exit | Meaning |", "|---|---|"]
    rows += [f"| {row['exit']} | {row['sentence']} |" for row in catalog.exits()]
    return "\n".join(rows) + "\n"


def _errors() -> str:
    """Every error code with its sentence and the exit code its refusal takes."""
    rows = ["\n| Code | Exit | Meaning |", "|---|---|---|"]
    rows += [f"| `{row['code']}` | {row['exit']} | {row['sentence']} |" for row in catalog.document()["errors"]]
    return "\n".join(rows) + "\n"


def _findings() -> str:
    """Every finding code with its certainty and its sentence."""
    rows = ["\n| Code | Certainty | Meaning |", "|---|---|---|"]
    rows += [f"| `{row['code']}` | {row['certainty']} | {row['sentence']} |" for row in catalog.document()["findings"]]
    return "\n".join(rows) + "\n"


def _schema_names() -> str:
    """Every name `decktalk schema NAME` answers to, which is the whole contract in one list."""
    names = ", ".join(f"`{name}`" for name in catalog.names())
    return f"\n## The contract\n\n`decktalk schema` prints the whole instruction set. `decktalk schema NAME` takes {names}.\n"


def main(argv: list[str] | None = None) -> int:
    """Write the page, or say that the committed one would change."""
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="write the page")
    action.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = parser.parse_args(argv)
    written = page()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != written:
            print(f"{TARGET.relative_to(ROOT)} is out of date. Run `uv run scripts/build_cli_reference.py --write`.")
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(written, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
