# /// script
# requires-python = ">=3.12"
# ///
"""Generate the settings reference from the committed JSON Schema.

    uv run scripts/build_settings_reference.py            # write the page
    uv run scripts/build_settings_reference.py --check    # exit 1 if the committed page would change

The page is a rendering of the published schema by construction. It reads `schema/decktalk-1.json`
rather than the dataclasses, so a reader of the page and a machine reading the schema are told the
same thing by the same bytes, and a key that reached the page without reaching the schema is
impossible rather than merely unlikely.

It opens with the index from a verdict to the keys that move it, because that is the lookup an
agent makes after a failure, and it ends with the numbers that are deliberately not knobs, because
the second lookup an agent makes is for a knob that does not exist.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "decktalk-1.json"
TARGET = ROOT / "docs" / "reference" / "configuration.mdx"

HEADER = """---
title: Configuration
description: Every DeckTalk setting, with its safe range, its unit, and the failures it decides.
---

{/* Generated by scripts/build_settings_reference.py from schema/decktalk-1.json. Do not edit by hand. */}

A setting is a number or a word a project could reasonably hold differently, and which some
judgement names when it fails. Every one below publishes the range that is safe to turn it through,
its true unit, the file it belongs in, and the findings its value moves. The range is the range the
loader enforces: a value outside it is refused by name, with the range it left, before any stage
runs, because a published bound you can cross into nonsense is worse than no bound at all.

Bind the schema to your project file and an editor completes every key as you type it.

```toml decktalk.toml
#:schema https://decktalk.ai/schema/decktalk-1.json

[verify]
cue_offset_max_ms = 120
```

## Which value wins

Five layers can set a key. Each one overrides the layers before it.

1. The default in the table below.
2. The same table in the per-machine settings file.
3. The same table in the project's `decktalk.toml`.
4. The environment variable each key publishes, such as `DECKTALK_VIDEO_PRESET`.
5. `--set table.key=value`, on any command, for one run.

`decktalk config explain KEY` prints those five layers with the winner marked, so you never have to
work out which one is in force.

The per-machine settings file holds machine keys alone. A key about the film in that file is
refused by name, because the file that ships has to carry whatever the machine running it believes.

| Linux | macOS | Windows |
|---|---|---|
| `$XDG_CONFIG_HOME/decktalk/decktalk.toml`, or `~/.config/decktalk/decktalk.toml` | `~/Library/Application Support/decktalk/decktalk.toml` | `%APPDATA%\\decktalk\\decktalk.toml` |
"""

FOOTER = """## Related

- **Set the sections, the voice and the mix:** [decktalk.toml](/reference/decktalk-toml)
- **Read the `[verify]` limits in context:** [Verify](/reference/verify)
- **Turn a key for one run:** [CLI](/reference/cli)
"""

INDEX_LEAD = """## Which key moves which failure

A finding names the key that decided it. This is the same index in reverse, for the case where you
have a code and want the candidates before you run anything.
"""

NUMBERS_LEAD = """## The numbers that are not knobs

These are the numbers that decide something and are still not settings. A derived number is written
as its expression, so it follows the keys it reads at every frame size and every rate. A constant is
a fact about a codec, a standard, or a tool DeckTalk drives, and it is fixed for the same reason a
sample rate is. Neither can be set, and both are here so that a knob you cannot find is a number you
can read.
"""


def schema() -> dict[str, Any]:
    """The committed schema, which is the one thing this page renders."""
    return json.loads(SCHEMA.read_text(encoding="utf-8"))


def keys(document: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """Every tuning key of the schema as (table, name, property), in the order the schema declares them."""
    out: list[tuple[str, str, dict[str, Any]]] = []
    for table, body in document["properties"].items():
        if body.get("x-kind") == "document":
            continue
        out += _walk(table, body)
    return out


def _walk(table: str, body: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """One table's own keys, then the keys of every table nested inside it."""
    own = [(table, name, prop) for name, prop in body.get("properties", {}).items() if "x-scope" in prop]
    nested: list[tuple[str, str, dict[str, Any]]] = []
    for name, prop in body.get("properties", {}).items():
        if "x-scope" not in prop:
            nested += _walk(f"{table}.{name}", prop)
    return own + nested


def cell(text: object) -> str:
    """One value in a table cell, with the pipe that would end the cell escaped."""
    return str(text).replace("|", "\\|")


def toml_value(value: object) -> str:
    """One default as it would be written in `decktalk.toml`."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(x) for x in value) + "]"
    return str(value)


def index(rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """The verdict-to-keys index, which is the lookup an agent makes with a code and nothing else."""
    by_code: dict[str, list[str]] = {}
    for table, name, prop in rows:
        for code in prop.get("x-decides", []):
            by_code.setdefault(code, []).append(f"`{table}.{name}`")
    out = [INDEX_LEAD, "| Finding | Keys that move it |", "|---|---|"]
    out += [f"| `{code}` | {', '.join(by_code[code])} |" for code in sorted(by_code)]
    return [*out, ""]


def tables(document: dict[str, Any], rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """One section per table, each a row per key with everything the schema publishes about it."""
    out: list[str] = []
    for table in dict.fromkeys(name for name, _key, _property in rows):
        body = _table(document, table)
        out.append(f"## `[{table}]`\n")
        out.append(f"{body['description']}\n")
        out.append("| Key | Type | Default | Safe range | Unit | Decides | Meaning |")
        out.append("|---|---|---|---|---|---|---|")
        for name, prop in ((name, prop) for t, name, prop in rows if t == table):
            decides = ", ".join(f"`{code}`" for code in prop.get("x-decides", []))
            out.append(
                f"| `{name}` | {prop['type']} | `{toml_value(prop['default'])}` | {cell(prop['x-range'])} "
                f"| {prop.get('x-unit', '')} | {decides} | {cell(prop['description'])} |"
            )
        out.append("")
        out += hazards(table, rows)
    return out


def hazards(table: str, rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """The hazard sentences of one table, which say what the refusal at each edge is protecting."""
    found = [(name, prop) for t, name, prop in rows if t == table and "x-hazard" in prop]
    if not found:
        return []
    return ["<Warning>", *[f"**`{table}.{name}`** {prop['x-hazard']}\n" for name, prop in found], "</Warning>", ""]


def _table(document: dict[str, Any], dotted: str) -> dict[str, Any]:
    """One table of the schema by its dotted name."""
    outer, *inner = dotted.split(".")
    body = document["properties"][outer]
    for part in inner:
        body = body["properties"][part]
    return body


def numbers(document: dict[str, Any]) -> list[str]:
    """The `x-numbers` array as the page's closing section, which is where a missing knob is explained."""
    out = [NUMBERS_LEAD, "| Number | Kind | Formula | At the defaults | Why |", "|---|---|---|---|---|"]
    for number in document["x-numbers"]:
        unit = f" {number['unit']}" if number["unit"] else ""
        out.append(
            f"| `{number['id']}` | {number['kind']} | `{cell(number['formula'])}` "
            f"| {number['value']}{unit} | {cell(number['description'])} |"
        )
    return [*out, ""]


def render() -> str:
    """The whole page, which is the header, the index, one section per table, the numbers and the links."""
    document = schema()
    rows = keys(document)
    parts = [HEADER, *index(rows), *tables(document, rows), *numbers(document), FOOTER]
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"stale: {TARGET.relative_to(ROOT)}. Run `uv run scripts/build_settings_reference.py`.")
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
