"""Generate the skills table in docs/agents/skills.mdx from the packaged SKILL.md front matter.

    uv run scripts/build_skills_list.py --write    # write the table
    uv run scripts/build_skills_list.py --check    # exit 1 if the committed page would change

Each row is one packaged skill: its name, when it starts and what it leaves behind. The name is the
skill's own `name`, and when it starts is the sentence of its `description` that opens "Use when ",
or its first sentence when none does, so the page and the skill cannot say different things about
when to reach for it.
The last column is the skill's `metadata.ends_with`, which is the one line the page needs and a
reader of the skill does not.

Everything outside the table is prose in the page itself.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

import generated
from decktalk.template import SKILL_NAMES
from decktalk.toolchain import assets

ROOT = Path(__file__).resolve().parent.parent

TARGET = ROOT / "docs" / "agents" / "skills.mdx"

MARKERS = ("{/* skills:start */}", "{/* skills:end */}")


def front_matter(text: str) -> dict[str, str]:
    """The skill's front matter as an agent's YAML loader reads it, with `metadata` lifted beside `name`.

    `metadata.ends_with` arrives as `ends_with`, because the front matter's keys are fixed and a
    page-only line lives under `metadata` rather than beside `name` and `description`. A value that
    is not valid YAML stops the run here, because every harness that loads the skill would refuse it.
    """
    doc = yaml.safe_load(text[4:].partition("\n---\n")[0])
    return {**doc, **doc["metadata"]}


def trigger(description: str) -> str:
    """The sentence of a description that says when to use the skill, as the table's middle column."""
    for sentence in re.split(r"(?<=\.)\s+", description):
        if sentence.startswith("Use when "):
            return sentence[len("Use when ") :].strip()
    return description.split(". ")[0].strip() + "."


def rows() -> list[str]:
    """One row per packaged skill, in the order an author meets them, which the package declares."""
    out: list[str] = []
    for name in SKILL_NAMES:
        doc = front_matter((assets.package_file("skills") / name / "SKILL.md").read_text(encoding="utf-8"))
        out.append(f"| `{doc['name']}` | {trigger(doc['description'])} | {doc['ends_with'].rstrip()} |")
    return out


def documents() -> dict[Path, str]:
    """The skills page with its table written from the packaged skills, and every other line kept."""
    table = "\n".join(["| Skill | It starts when | It ends with |", "|---|---|---|", *rows()])
    block = f"\n{{/* Generated by scripts/build_skills_list.py. Do not edit by hand. */}}\n\n{table}\n"
    return {TARGET: generated.splice(TARGET.read_text(encoding="utf-8"), MARKERS, block, where=TARGET)}


if __name__ == "__main__":
    sys.exit(generated.run(documents))
