"""Generate the settings reference from the JSON Schema of decktalk.toml.

    uv run scripts/build_settings_reference.py --write    # write the page
    uv run scripts/build_settings_reference.py --check    # exit 1 if the committed page would change

The page is a rendering of the published schema by construction. It reads the document
`build_settings_schema.py` writes to `schemas/v1/decktalk.json` rather than the dataclasses, so a
reader of the page and a machine reading the schema are told the same thing, and a key that reached
the page without reaching the schema is impossible rather than merely unlikely. It asks that script
rather than the committed file, so the two can be written in either order.

It names the keys only a machine may set, because a project file that sets one is refused. It then
gives the index from a verdict to the keys that move it, because that is the lookup an agent makes
after a failure, and it ends with the numbers that are deliberately not knobs, because the second
lookup an agent makes is for a knob that does not exist.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import tomlkit

import build_settings_schema
import generated

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "reference" / "configuration.mdx"

HEADER = """---
title: Configuration
description: Every DeckTalk setting, with its safe range, its unit, and the failures it decides.
---

{/* Generated by scripts/build_settings_reference.py from schemas/v1/decktalk.json. Do not edit by hand. */}

A setting is a number or a word a project could reasonably hold differently, and which some
judgement names when it fails. Every one below publishes the range that is safe to turn it through,
its true unit, the file it belongs in, and the findings its value moves. The range is the range the
loader enforces: a value outside it is refused by name, with the range it left, before any stage
runs, because a published bound you can cross into nonsense is worse than no bound at all.

Bind the schema to your project file and an editor completes every key as you type it.

```toml decktalk.toml
#:schema https://raw.githubusercontent.com/jacobcbeaudin/decktalk/main/schemas/v1/decktalk.json

[verify]
cue_offset_max_ms = 120
```

## Which value wins

Five layers can set a key. Each one overrides the layers before it.

1. The default in the table below.
2. The same table in the per-machine settings file.
3. The same table in the project's `decktalk.toml`.
4. The environment variable each key publishes, such as `DECKTALK_VIDEO_PRESET`.
5. `--set table.key=value`, on any command, for one run.

`decktalk config explain KEY` prints those five layers with the winner marked, so you never have to
work out which one is in force.

The per-machine settings file holds machine keys alone. A key about the film in that file is
refused by name, because the file that ships has to carry whatever the machine running it believes.
`DECKTALK_CONFIG` names a different per-machine file.

| Linux | macOS | Windows |
|---|---|---|
| `$XDG_CONFIG_HOME/decktalk/decktalk.toml`, or `~/.config/decktalk/decktalk.toml` | `~/Library/Application Support/decktalk/decktalk.toml` | `%APPDATA%\\decktalk\\decktalk.toml` |
"""

FOOTER = """## Related

- **Set the sections, the voice and the mix:** [decktalk.toml](/reference/decktalk-toml)
- **Read the `[verify]` limits in context:** [Verify](/reference/verify)
- **Turn a key for one run:** [CLI](/reference/cli)
"""

INDEX_LEAD = """## Which key moves which failure

A finding names the key that decided it. This is the same index in reverse, for the case where you
have a code and want the candidates before you run anything.
"""

MACHINE_LEAD = """## Keys only a machine may set

These keys describe the machine rather than the film: where a tool or a cache lives, and how hard
this machine may be driven. A project file that sets one is refused by name, because a project
travels and a path or a limit that is right on one machine is wrong on the next. Write one into this
machine's file with `decktalk config set KEY VALUE --where machine`, or set its environment variable.
"""

NUMBERS_LEAD = """## The numbers that are not knobs

These are the numbers that decide something and are still not settings. A derived number is written
as its expression, so it follows the keys it reads at every frame size and every rate. A constant is
a fact about a codec, a standard, or a tool DeckTalk drives, and it is fixed for the same reason a
sample rate is. Neither can be set, and both are here so that a knob you cannot find is a number you
can read.
"""


def keys(document: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """Every tuning key of the schema as (table, name, property), in the order the schema declares them."""
    out: list[tuple[str, str, dict[str, Any]]] = []
    for table, body in document["properties"].items():
        if body.get("x-kind") == "document":
            continue
        out += _walk(table, body)
    return out


def _walk(table: str, body: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """One table's own keys, then the keys of every table nested inside it."""
    own = [(table, name, prop) for name, prop in body.get("properties", {}).items() if "x-scope" in prop]
    nested: list[tuple[str, str, dict[str, Any]]] = []
    for name, prop in body.get("properties", {}).items():
        if "x-scope" not in prop:
            nested += _walk(f"{table}.{name}", prop)
    return own + nested


def cell(text: object) -> str:
    """One value in a table cell, with the pipe that would end the cell escaped."""
    return str(text).replace("|", "\\|")


def index(rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """The verdict-to-keys index, which is the lookup an agent makes with a code and nothing else."""
    by_code: dict[str, list[str]] = {}
    for table, name, prop in rows:
        for code in prop.get("x-decides", []):
            by_code.setdefault(code, []).append(f"`{table}.{name}`")
    out = [INDEX_LEAD, "| Finding | Keys that move it |", "|---|---|"]
    out += [f"| `{code}` | {', '.join(by_code[code])} |" for code in sorted(by_code)]
    return [*out, ""]


def machine(rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """The keys a project file may not set, which is the list a refused `config set` points at."""
    found = [f"`{table}.{name}`" for table, name, prop in rows if prop["x-scope"] == "machine"]
    return [MACHINE_LEAD, ", ".join(found[:-1]) + f" and {found[-1]}." if len(found) > 1 else f"{found[0]}.", ""]


def tables(document: dict[str, Any], rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """One section per table, each a row per key with everything the schema publishes about it."""
    out: list[str] = []
    for table in dict.fromkeys(name for name, _key, _property in rows):
        body = _table(document, table)
        out.append(f"## `[{table}]`\n")
        out.append(f"{body['description']}\n")
        out.append("| Key | Type | Default | Safe range | Unit | Scope | Decides | Meaning |")
        out.append("|---|---|---|---|---|---|---|---|")
        for name, prop in ((name, prop) for t, name, prop in rows if t == table):
            decides = ", ".join(f"`{code}`" for code in prop.get("x-decides", []))
            # tomlkit writes the default as `decktalk.toml` would hold it, escapes and all.
            default = tomlkit.item(prop["default"]).as_string()
            out.append(
                f"| `{name}` | {prop['type']} | `{default}` | {cell(prop['x-range'])} "
                f"| {prop.get('x-unit', '')} | {prop['x-scope']} | {decides} | {cell(prop['description'])} |"
            )
        out.append("")
        out += hazards(table, rows)
    return out


def hazards(table: str, rows: list[tuple[str, str, dict[str, Any]]]) -> list[str]:
    """The hazard sentences of one table, which say what the refusal at each edge is protecting."""
    found = [(name, prop) for t, name, prop in rows if t == table and "x-hazard" in prop]
    if not found:
        return []
    return ["<Warning>", *[f"**`{table}.{name}`** {prop['x-hazard']}\n" for name, prop in found], "</Warning>", ""]


def _table(document: dict[str, Any], dotted: str) -> dict[str, Any]:
    """One table of the schema by its dotted name."""
    outer, *inner = dotted.split(".")
    body = document["properties"][outer]
    for part in inner:
        body = body["properties"][part]
    return body


def numbers(document: dict[str, Any]) -> list[str]:
    """The `x-numbers` array as the page's closing section, which is where a missing knob is explained."""
    out = [NUMBERS_LEAD, "| Number | Kind | Formula | At the defaults | Why |", "|---|---|---|---|---|"]
    for number in document["x-numbers"]:
        unit = f" {number['unit']}" if number["unit"] else ""
        out.append(
            f"| `{number['id']}` | {number['kind']} | `{cell(number['formula'])}` "
            f"| {number['value']}{unit} | {cell(number['description'])} |"
        )
    return [*out, ""]


def render() -> str:
    """The whole page, which is the header, the index, one section per table, the numbers and the links."""
    document = build_settings_schema.document(machine=False)
    rows = keys(document)
    parts = [HEADER, *machine(rows), *index(rows), *tables(document, rows), *numbers(document), FOOTER]
    return "\n".join(parts).rstrip() + "\n"


def documents() -> dict[Path, str]:
    """The settings reference, which is the one file this generator owns."""
    return {TARGET: render()}


if __name__ == "__main__":
    sys.exit(generated.run(documents))
