# /// script
# requires-python = ">=3.12"
# ///
"""Keep the command tree in AGENTS.md equal to the command tree the code has.

    uv run scripts/build_agents_doc.py --write    # write the block
    uv run scripts/build_agents_doc.py --check    # exit 1 if the committed block would change

`AGENTS.md` is prose an agent reads before it touches this repository, and prose is written by hand.
The one part of it that goes stale on its own is the list of commands, so that block is written from
the same walk over the parser that `decktalk schema` prints, between two markers, and everything
around it is left alone.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from decktalk.cli import catalog  # noqa: E402  (after sys.path, so a checkout needs no install)
from decktalk.cli.options import Group  # noqa: E402

TARGET = ROOT / "AGENTS.md"

OPEN = "<!-- commands: generated by scripts/build_agents_doc.py -->"
CLOSE = "<!-- end commands -->"


def block() -> str:
    """The command tree as one block, grouped the way the help groups it."""
    lines: list[str] = []
    for group in Group:
        rows = [row for row in catalog.walk() if row["group"] == group.value]
        if not rows:
            continue
        lines.append(f"\n{group.value}:\n")
        width = max(len(row["command"]) for row in catalog.walk())
        lines += [f"  {row['command'].ljust(width)}  {row['purpose']}\n" for row in rows]
    return f"{OPEN}\n```text{''.join(lines)}```\n{CLOSE}"


def written(current: str) -> str:
    """The file with its command block replaced, and every other line of it left as it was."""
    if OPEN not in current or CLOSE not in current:
        raise SystemExit(f"{TARGET.name} has no command block. Put {OPEN} and {CLOSE} where it belongs.")
    head, _, rest = current.partition(OPEN)
    _, _, tail = rest.partition(CLOSE)
    return f"{head}{block()}{tail}"


def main(argv: list[str] | None = None) -> int:
    """Write the block, or say that the committed one would change."""
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="write the block")
    action.add_argument("--check", action="store_true", help="exit 1 if the committed block would change")
    args = parser.parse_args(argv)
    current = TARGET.read_text(encoding="utf-8")
    fresh = written(current)
    if args.check:
        if current != fresh:
            print(f"{TARGET.name} is out of date. Run `uv run scripts/build_agents_doc.py --write`.")
            return 1
        return 0
    TARGET.write_text(fresh, encoding="utf-8")
    print(f"Wrote {TARGET.name}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
