# /// script
# requires-python = ">=3.12"
# ///
"""Generate one docs page per error code and per finding code, from the enums that declare them.

    uv run scripts/build_code_pages.py --write    # write every page
    uv run scripts/build_code_pages.py --check    # exit 1 if a committed page would change

Every error block and every finding line prints a docs URL, so the page for a code lands with the
code and resolves from the first run. The sentence, the certainty, the exit code and the settings
keys a code depends on come from the enum member, so a page cannot say something the code does not.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from decktalk.errors import ErrorCode  # noqa: E402  (after sys.path, so a checkout needs no install)
from decktalk.findings import Code  # noqa: E402

ERRORS = ROOT / "docs" / "reference" / "errors"
FINDINGS = ROOT / "docs" / "reference" / "findings"
GENERATED = "{/* Generated by scripts/build_code_pages.py from the enums in src/decktalk. Do not edit by hand. */}"
STALE = "stale: {path}. Run `uv run scripts/{script} --write` to bring it up to date."


def page(title: str, description: str, body: list[str]) -> str:
    """One docs page as it is committed, which is the frontmatter, the notice and the rows."""
    lines = ["---", f"title: {title}", f"description: {description}", "---", "", GENERATED, "", *body]
    return "\n".join(lines).rstrip() + "\n"


def error_page(code: ErrorCode) -> str:
    """The page for one error code, which is what the printed error block links to."""
    return page(
        title=code.value,
        description=code.sentence,
        body=[
            code.sentence,
            "",
            f"A command that ends this way exits {code.exit_code}. The JSON object carries `error.code` of",
            f"`{code.value}`, one sentence in `error.message`, and the whole command that would clear it in",
            "`error.hint`.",
        ],
    )


def finding_page(code: Code) -> str:
    """The page for one finding code, which is what the printed finding line links to."""
    decides = ", ".join(f"`{key}`" for key in code.decides)
    body = [
        code.sentence,
        "",
        f"This finding is {code.certainty.value}, and {code.raised_by.sentence}.",
        f"Pass `--allow {code.value}` to carry on past it, and `--fail-on` to choose which certainty fails a run.",
    ]
    if decides:
        body += ["", f"The settings that move this verdict are {decides}."]
    return page(title=code.value, description=code.sentence, body=body)


def documents() -> dict[Path, str]:
    """Every page this generator owns, by the path it is written to."""
    pages = {ERRORS / f"{code.value}.mdx": error_page(code) for code in ErrorCode}
    pages |= {FINDINGS / f"{code.value}.mdx": finding_page(code) for code in Code}
    return pages


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="write every page")
    action.add_argument("--check", action="store_true", help="exit 1 if a committed page would change")
    args = parser.parse_args()

    wanted = documents()
    if args.check:
        stale = [path for path, text in wanted.items() if not path.exists() or path.read_text("utf-8") != text]
        stale += [p for d in (ERRORS, FINDINGS) if d.is_dir() for p in sorted(d.glob("*.mdx")) if p not in wanted]
        for path in stale:
            print(STALE.format(path=path.relative_to(ROOT), script=Path(__file__).name))
        return 1 if stale else 0

    for directory in (ERRORS, FINDINGS):
        directory.mkdir(parents=True, exist_ok=True)
        for path in sorted(directory.glob("*.mdx")):
            if path not in wanted:
                path.unlink()
    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(wanted)} pages into {ERRORS.relative_to(ROOT)} and {FINDINGS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
