"""Generate one docs page per error code and per finding code, from the enums that declare them.

    uv run scripts/build_code_pages.py --write    # write every page
    uv run scripts/build_code_pages.py --check    # exit 1 if a committed page would change

Every error block and every finding line prints a docs URL, so the page for a code lands with the
code and resolves from the first run. The sentence, the certainty, the exit code and the settings
keys a code depends on come from the enum member and from the keys that name it, so a page cannot
say something the code does not.

It also writes the table of the codes the page raises into the runtime reference, between two
markers, because that table was once typed by hand and described eleven codes differently from the
pages this script writes.
"""

from __future__ import annotations

import sys
from pathlib import Path

import generated
from decktalk.cli import catalog
from decktalk.errors import ErrorCode
from decktalk.findings import Code, RaisedBy

ROOT = Path(__file__).resolve().parent.parent

RUNTIME = ROOT / "docs" / "reference" / "runtime.mdx"
ERRORS = ROOT / "docs" / "reference" / "errors"
FINDINGS = ROOT / "docs" / "reference" / "findings"
GENERATED = "{/* Generated by scripts/build_code_pages.py from the enums in src/decktalk. Do not edit by hand. */}"
TABLE = ("{/* page codes: generated by scripts/build_code_pages.py */}", "{/* end page codes */}")
"""The markers around the runtime reference's code table, which is the one part of that page written here."""


def page(title: str, description: str, body: list[str]) -> str:
    """One docs page as it is committed, which is the frontmatter, the notice and the rows."""
    lines = ["---", f"title: {title}", f"description: {description}", "---", "", GENERATED, "", *body]
    return "\n".join(lines).rstrip() + "\n"


def error_page(code: ErrorCode) -> str:
    """The page for one error code, which is what the printed error block links to."""
    return page(
        title=code.value,
        description=code.sentence,
        body=[
            code.sentence,
            "",
            f"A command that ends this way exits {code.exit_code}. The JSON object carries `error.code` of",
            f"`{code.value}`, one sentence in `error.message`, and the whole command that would clear it in",
            "`error.hint`.",
        ],
    )


def finding_page(code: Code) -> str:
    """The page for one finding code, which is what the printed finding line links to."""
    decides = ", ".join(f"`{key}`" for key in catalog.deciding(code))
    body = [
        code.sentence,
        "",
        f"This finding is {code.certainty.value}, and {code.raised_by.sentence}.",
        f"Pass `--allow {code.value}` to carry on past it, and `--fail-on` to choose which certainty fails a run.",
    ]
    if decides:
        body += ["", f"The settings that move this verdict are {decides}."]
    return page(title=code.value, description=code.sentence, body=body)


def documents() -> dict[Path, str]:
    """Every page this generator owns, and the runtime reference with its table of the codes the page raises."""
    pages = {ERRORS / f"{code.value}.mdx": error_page(code) for code in ErrorCode}
    pages |= {FINDINGS / f"{code.value}.mdx": finding_page(code) for code in Code}
    rows = ["| Code | What the page could not honour |", "|---|---|"]
    rows += [f"| `{code.value}` | {code.sentence} |" for code in Code if code.raised_by is RaisedBy.RUNTIME]
    table = "\n".join(["", "", *rows, "", ""])
    pages[RUNTIME] = generated.splice(RUNTIME.read_text(encoding="utf-8"), TABLE, table, where=RUNTIME)
    return pages


if __name__ == "__main__":
    sys.exit(generated.run(documents, owned=[ERRORS / "*.mdx", FINDINGS / "*.mdx"]))
