# /// script
# requires-python = ">=3.12"
# ///
"""Generate docs/reference/configuration.mdx from the dataclasses in src/decktalk/config.py.

    uv run scripts/build_config_reference.py            # write the page
    uv run scripts/build_config_reference.py --check    # exit 1 if the committed page would change

Every field, its type, its default, and the comment beside it come from the source, so the
reference cannot drift from the code. Edit config.py, then run this.
"""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "decktalk" / "config.py"
TARGET = ROOT / "docs" / "reference" / "configuration.mdx"

HEADER = """---
title: Configuration
description: Look up every DeckTalk tuning field, with its type, its default, and what it changes.
---

{/* Generated by scripts/build_config_reference.py from src/decktalk/config.py. Do not edit by hand. */}

Tuning fields change how DeckTalk records, assembles, and checks a video. This page lists every
field, grouped by table, with its type and its default.

A tuning table can go in the project's `decktalk.toml`. The same field can also come from an
environment variable.

```toml decktalk.toml
[video]
preset = "veryfast"
```

```console
DECKTALK_VIDEO_PRESET=veryfast decktalk build --no-voice
```

The scaffold builds with every default. Change `[video]` for faster drafts. Change `[verify]` when a
small reveal fails the cue check.

## Which value wins

Five layers can set a field. Each layer overrides the layers before it.

1. The default on this page.
2. The same table in the per-machine settings file.
3. The same table in the project's `decktalk.toml`.
4. An environment variable named `DECKTALK_<TABLE>_<FIELD>`, such as `DECKTALK_VIDEO_PRESET`.
5. A command-line flag, for one run.

The per-machine settings file is in a different place on each platform.

| Linux | macOS | Windows |
|---|---|---|
| `$XDG_CONFIG_HOME/decktalk/decktalk.toml`, or `~/.config/decktalk/decktalk.toml` when `XDG_CONFIG_HOME` is not set | `~/Library/Application Support/decktalk/decktalk.toml` | `%APPDATA%\\decktalk\\decktalk.toml` |

Note: `DECKTALK_CONFIG` points at a different file. The per-machine file can hold only the tables on
this page, and any other table fails the load. `decktalk doctor` prints the path in its `config` row.

An environment variable for an array field takes comma-separated values, such as
`DECKTALK_VERIFY_PROBE_DELAYS=0.7,1.5`.

Four flags override a field for one run.

| Flag | Commands | Overrides |
|---|---|---|
| `--preset` | `assemble`, `build` | `[video] preset` |
| `--crf` | `assemble`, `build` | `[video] crf` |
| `--settle` | `record` | `[record] settle_seconds` |
| `--model` | `narrate` | `[narration] model` and `[voice] model` |

Sections, the voice, mix levels, and soundscape prompts are project content, not tuning.
[decktalk.toml](/reference/decktalk-toml) lists those tables. Secrets go only in `.env`.
"""

FOOTER = """## Related

- **Set sections, the voice, and the mix:** [decktalk.toml](/reference/decktalk-toml)
- **Understand the `[verify]` fields:** [Verify](/reference/verify)
- **Override a field for one run:** [CLI](/reference/cli)
"""

# The words the docs use for types (style rule S22), keyed by the annotation in config.py.
TYPE_WORDS = {
    "int": "integer",
    "float": "number",
    "str": "string",
    "bool": "boolean",
    "tuple[float, ...]": "array of numbers",
}


@dataclass
class Field:
    name: str
    type: str
    default: str
    comment: str


@dataclass
class Section:
    key: str
    cls: str
    doc: str
    fields: list[Field]


def toml_value(node: ast.expr | None) -> str:
    """The default as it would be written in decktalk.toml, or the Python source when it is not a literal."""
    if node is None:
        return ""
    try:
        value = ast.literal_eval(node)
    except ValueError:
        return ast.unparse(node)

    def fmt(v: object) -> str:
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, str):
            return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
        if isinstance(v, tuple | list):
            return "[" + ", ".join(fmt(x) for x in v) + "]"
        return repr(v)

    return fmt(value)


def parse(source: Path) -> list[Section]:
    tree = ast.parse(source.read_text(encoding="utf-8"))
    lines = source.read_text(encoding="utf-8").splitlines()
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    settings = classes["Settings"]
    out: list[Section] = []
    for node in settings.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        cls = classes[ast.unparse(node.annotation)]
        fields: list[Field] = []
        for item in cls.body:
            if not isinstance(item, ast.AnnAssign) or not isinstance(item.target, ast.Name):
                continue
            line = lines[item.lineno - 1]
            comment = line.split("#", 1)[1].strip() if "#" in line else ""
            # A comment that does not fit on the field's line continues on the comment lines right below it.
            j = item.end_lineno or item.lineno
            while comment and j < len(lines) and lines[j].strip().startswith("#"):
                comment += " " + lines[j].strip().removeprefix("#").strip()
                j += 1
            annotation = ast.unparse(item.annotation)
            fields.append(
                Field(item.target.id, TYPE_WORDS.get(annotation, annotation), toml_value(item.value), comment)
            )
        out.append(Section(node.target.id, cls.name, ast.get_docstring(cls) or "", fields))
    return out


def render(sections: list[Section]) -> str:
    parts = [HEADER]
    for s in sections:
        parts.append(f"## `[{s.key}]`\n")
        if s.doc:
            parts.append(f"{s.doc} Environment variables start with `DECKTALK_{s.key.upper()}_`.\n")
        else:
            parts.append(f"Environment variables start with `DECKTALK_{s.key.upper()}_`.\n")
        parts.append("| Field | Type | Default | Meaning |\n|---|---|---|---|")
        for f in s.fields:
            default = f"`{f.default}`" if f.default else ""
            parts.append(f"| `{f.name}` | `{f.type}` | {default} | {f.comment} |")
        parts.append("")
    parts.append(FOOTER)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed page would change")
    args = ap.parse_args()
    text = render(parse(SOURCE))
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"stale: {TARGET.relative_to(ROOT)}")
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
