"""Keep the command tree in AGENTS.md equal to the command tree the code has.

    uv run scripts/build_agents_doc.py --write    # write the block
    uv run scripts/build_agents_doc.py --check    # exit 1 if the committed block would change

`AGENTS.md` is prose an agent reads before it touches this repository, and prose is written by hand.
The one part of it that goes stale on its own is the list of commands, so that block is written from
the same walk over the parser that `decktalk schema` prints, between two markers, and everything
around it is left alone.
"""

from __future__ import annotations

import sys
from pathlib import Path

import generated
from decktalk.cli import catalog
from decktalk.cli.options import Group

ROOT = Path(__file__).resolve().parent.parent

TARGET = ROOT / "AGENTS.md"

MARKERS = ("<!-- commands: generated by scripts/build_agents_doc.py -->", "<!-- end commands -->")


def documents() -> dict[Path, str]:
    """AGENTS.md with its command tree, grouped the way the help groups it, and every other line kept."""
    lines: list[str] = []
    width = max(len(row["command"]) for row in catalog.walk())
    for group in Group:
        rows = [row for row in catalog.walk() if row["group"] == group.value]
        if rows:
            lines.append(f"\n{group.value}:\n")
            lines += [f"  {row['command'].ljust(width)}  {row['purpose']}\n" for row in rows]
    block = f"\n```text{''.join(lines)}```\n"
    return {TARGET: generated.splice(TARGET.read_text(encoding="utf-8"), MARKERS, block, where=TARGET)}


if __name__ == "__main__":
    sys.exit(generated.run(documents))
